<?php
// This script and data application were generated by AppGini 5.31
// Download AppGini for free from http://bigprof.com/appgini/download/

/*
	ajax-callable script that returns code for either a combo drop-down or an auto-complete
	drop-down, based on number of items.

	REQUEST parameters:
	===============
	t: table name
	f: lookup field name
	id: selected id
	p: page number (default = 1)
	s: search term
	o: 0 (default) for text-only or 1 for full options list
	text: selected text
	filterer_[filterer]: name of filterer field to be used to filter the drop-down contents
				must be one of the filteres defined for the concerned field
*/

	$start_ts = microtime(true);

	// how many results to return per call, in case of json output
	$results_per_page = 50;

	$curr_dir = dirname(__FILE__);
	include("$curr_dir/defaultLang.php");
	include("$curr_dir/language.php");
	include("$curr_dir/lib.php");

	// drop-downs config
	$lookups = array(   
		'biblio_author' => array(   
			'agenttype1' => array(
				'parent_table' => 'class_agent_type1',
				'parent_pk_field' => 'id',
				'parent_caption' => '`class_agent_type1`.`type`',
				'parent_from' => '`class_agent_type1` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'agenttype2' => array(
				'parent_table' => 'class_agent_type2',
				'parent_pk_field' => 'id',
				'parent_caption' => '`class_agent_type2`.`type`',
				'parent_from' => '`class_agent_type2` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'authority_organization' => array(
				'parent_table' => 'class_authority_agent',
				'parent_pk_field' => 'id',
				'parent_caption' => '`class_authority_agent`.`abbreviation`',
				'parent_from' => '`class_authority_agent` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			)
		),
		'biblio_doc' => array(   
			'author_name' => array(
				'parent_table' => 'biblio_author',
				'parent_pk_field' => 'id',
				'parent_caption' => 'IF(CHAR_LENGTH(`biblio_author`.`last_name`) || CHAR_LENGTH(`biblio_author`.`first_name`), CONCAT_WS(\'\', `biblio_author`.`last_name`, \', \', `biblio_author`.`first_name`), \'\')',
				'parent_from' => '`biblio_author` LEFT JOIN `class_agent_type1` as class_agent_type11 ON `class_agent_type11`.`id`=`biblio_author`.`agenttype1` LEFT JOIN `class_agent_type2` as class_agent_type21 ON `class_agent_type21`.`id`=`biblio_author`.`agenttype2` LEFT JOIN `class_authority_agent` as class_authority_agent1 ON `class_authority_agent1`.`id`=`biblio_author`.`authority_organization` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'author_id' => array(
				'parent_table' => 'biblio_author',
				'parent_pk_field' => 'id',
				'parent_caption' => '`biblio_author`.`id`',
				'parent_from' => '`biblio_author` LEFT JOIN `class_agent_type1` as class_agent_type11 ON `class_agent_type11`.`id`=`biblio_author`.`agenttype1` LEFT JOIN `class_agent_type2` as class_agent_type21 ON `class_agent_type21`.`id`=`biblio_author`.`agenttype2` LEFT JOIN `class_authority_agent` as class_authority_agent1 ON `class_authority_agent1`.`id`=`biblio_author`.`authority_organization` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'type' => array(
				'parent_table' => 'class_bibliography_type',
				'parent_pk_field' => 'id',
				'parent_caption' => '`class_bibliography_type`.`type`',
				'parent_from' => '`class_bibliography_type` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'genre' => array(
				'parent_table' => 'class_bibliography_genre',
				'parent_pk_field' => 'id',
				'parent_caption' => '`class_bibliography_genre`.`genre`',
				'parent_from' => '`class_bibliography_genre` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'language' => array(
				'parent_table' => 'class_language',
				'parent_pk_field' => 'id',
				'parent_caption' => '`class_language`.`language`',
				'parent_from' => '`class_language` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'rights' => array(
				'parent_table' => 'class_rights',
				'parent_pk_field' => 'id',
				'parent_caption' => '`class_rights`.`right`',
				'parent_from' => '`class_rights` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'authority_organization' => array(
				'parent_table' => 'class_authority_library',
				'parent_pk_field' => 'id',
				'parent_caption' => '`class_authority_library`.`authority_name`',
				'parent_from' => '`class_authority_library` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			)
		),
		'biblio_trascript' => array(   
			'author' => array(
				'parent_table' => 'biblio_author',
				'parent_pk_field' => 'id',
				'parent_caption' => 'IF(CHAR_LENGTH(`biblio_author`.`last_name`) || CHAR_LENGTH(`biblio_author`.`first_name`), CONCAT_WS(\'\', `biblio_author`.`last_name`, \',\', `biblio_author`.`first_name`), \'\')',
				'parent_from' => '`biblio_author` LEFT JOIN `class_agent_type1` as class_agent_type11 ON `class_agent_type11`.`id`=`biblio_author`.`agenttype1` LEFT JOIN `class_agent_type2` as class_agent_type21 ON `class_agent_type21`.`id`=`biblio_author`.`agenttype2` LEFT JOIN `class_authority_agent` as class_authority_agent1 ON `class_authority_agent1`.`id`=`biblio_author`.`authority_organization` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'author_memberID' => array(
				'parent_table' => 'biblio_author',
				'parent_pk_field' => 'id',
				'parent_caption' => '`biblio_author`.`memberID`',
				'parent_from' => '`biblio_author` LEFT JOIN `class_agent_type1` as class_agent_type11 ON `class_agent_type11`.`id`=`biblio_author`.`agenttype1` LEFT JOIN `class_agent_type2` as class_agent_type21 ON `class_agent_type21`.`id`=`biblio_author`.`agenttype2` LEFT JOIN `class_authority_agent` as class_authority_agent1 ON `class_authority_agent1`.`id`=`biblio_author`.`authority_organization` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'bibliography_id' => array(
				'parent_table' => 'biblio_doc',
				'parent_pk_field' => 'id',
				'parent_caption' => '`biblio_doc`.`id`',
				'parent_from' => '`biblio_doc` LEFT JOIN `biblio_author` as biblio_author1 ON `biblio_author1`.`id`=`biblio_doc`.`author_name` LEFT JOIN `class_bibliography_type` as class_bibliography_type1 ON `class_bibliography_type1`.`id`=`biblio_doc`.`type` LEFT JOIN `class_bibliography_genre` as class_bibliography_genre1 ON `class_bibliography_genre1`.`id`=`biblio_doc`.`genre` LEFT JOIN `class_language` as class_language1 ON `class_language1`.`id`=`biblio_doc`.`language` LEFT JOIN `class_rights` as class_rights1 ON `class_rights1`.`id`=`biblio_doc`.`rights` LEFT JOIN `class_authority_library` as class_authority_library1 ON `class_authority_library1`.`id`=`biblio_doc`.`authority_organization` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'bibliography_title' => array(
				'parent_table' => 'biblio_doc',
				'parent_pk_field' => 'id',
				'parent_caption' => '`biblio_doc`.`title`',
				'parent_from' => '`biblio_doc` LEFT JOIN `biblio_author` as biblio_author1 ON `biblio_author1`.`id`=`biblio_doc`.`author_name` LEFT JOIN `class_bibliography_type` as class_bibliography_type1 ON `class_bibliography_type1`.`id`=`biblio_doc`.`type` LEFT JOIN `class_bibliography_genre` as class_bibliography_genre1 ON `class_bibliography_genre1`.`id`=`biblio_doc`.`genre` LEFT JOIN `class_language` as class_language1 ON `class_language1`.`id`=`biblio_doc`.`language` LEFT JOIN `class_rights` as class_rights1 ON `class_rights1`.`id`=`biblio_doc`.`rights` LEFT JOIN `class_authority_library` as class_authority_library1 ON `class_authority_library1`.`id`=`biblio_doc`.`authority_organization` ',
				'filterers' => array('author' => 'author_name'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			)
		),
		'biblio_token' => array(   
			'author' => array(
				'parent_table' => 'biblio_author',
				'parent_pk_field' => 'id',
				'parent_caption' => 'IF(CHAR_LENGTH(`biblio_author`.`memberID`) || CHAR_LENGTH(`biblio_author`.`last_name`), CONCAT_WS(\'\', `biblio_author`.`memberID`, \'  \', `biblio_author`.`last_name`), \'\')',
				'parent_from' => '`biblio_author` LEFT JOIN `class_agent_type1` as class_agent_type11 ON `class_agent_type11`.`id`=`biblio_author`.`agenttype1` LEFT JOIN `class_agent_type2` as class_agent_type21 ON `class_agent_type21`.`id`=`biblio_author`.`agenttype2` LEFT JOIN `class_authority_agent` as class_authority_agent1 ON `class_authority_agent1`.`id`=`biblio_author`.`authority_organization` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'bibliography' => array(
				'parent_table' => 'biblio_doc',
				'parent_pk_field' => 'id',
				'parent_caption' => 'IF(CHAR_LENGTH(`biblio_doc`.`id`) || CHAR_LENGTH(`biblio_doc`.`title`), CONCAT_WS(\'\', `biblio_doc`.`id`, \'  \', `biblio_doc`.`title`), \'\')',
				'parent_from' => '`biblio_doc` LEFT JOIN `biblio_author` as biblio_author1 ON `biblio_author1`.`id`=`biblio_doc`.`author_name` LEFT JOIN `class_bibliography_type` as class_bibliography_type1 ON `class_bibliography_type1`.`id`=`biblio_doc`.`type` LEFT JOIN `class_bibliography_genre` as class_bibliography_genre1 ON `class_bibliography_genre1`.`id`=`biblio_doc`.`genre` LEFT JOIN `class_language` as class_language1 ON `class_language1`.`id`=`biblio_doc`.`language` LEFT JOIN `class_rights` as class_rights1 ON `class_rights1`.`id`=`biblio_doc`.`rights` LEFT JOIN `class_authority_library` as class_authority_library1 ON `class_authority_library1`.`id`=`biblio_doc`.`authority_organization` ',
				'filterers' => array('author' => 'author_name'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'transcript' => array(
				'parent_table' => 'biblio_trascript',
				'parent_pk_field' => 'id',
				'parent_caption' => 'IF(CHAR_LENGTH(`biblio_trascript`.`trascriber_memberID`) || CHAR_LENGTH(`biblio_trascript`.`transcript_title`), CONCAT_WS(\'\', `biblio_trascript`.`trascriber_memberID`, \'- \', `biblio_trascript`.`transcript_title`), \'\')',
				'parent_from' => '`biblio_trascript` LEFT JOIN `biblio_author` as biblio_author1 ON `biblio_author1`.`id`=`biblio_trascript`.`author` LEFT JOIN `biblio_doc` as biblio_doc1 ON `biblio_doc1`.`id`=`biblio_trascript`.`bibliography_title` ',
				'filterers' => array('author' => 'author', 'bibliography' => 'bibliography_id'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			)
		),
		'code_invivo' => array(   
			'author' => array(
				'parent_table' => 'biblio_author',
				'parent_pk_field' => 'id',
				'parent_caption' => 'IF(CHAR_LENGTH(`biblio_author`.`memberID`) || CHAR_LENGTH(`biblio_author`.`last_name`), CONCAT_WS(\'\', `biblio_author`.`memberID`, \'  \', `biblio_author`.`last_name`), \'\')',
				'parent_from' => '`biblio_author` LEFT JOIN `class_agent_type1` as class_agent_type11 ON `class_agent_type11`.`id`=`biblio_author`.`agenttype1` LEFT JOIN `class_agent_type2` as class_agent_type21 ON `class_agent_type21`.`id`=`biblio_author`.`agenttype2` LEFT JOIN `class_authority_agent` as class_authority_agent1 ON `class_authority_agent1`.`id`=`biblio_author`.`authority_organization` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'bibliography' => array(
				'parent_table' => 'biblio_doc',
				'parent_pk_field' => 'id',
				'parent_caption' => 'IF(CHAR_LENGTH(`biblio_doc`.`id`) || CHAR_LENGTH(`biblio_doc`.`title`), CONCAT_WS(\'\', `biblio_doc`.`id`, \'  \', `biblio_doc`.`title`), \'\')',
				'parent_from' => '`biblio_doc` LEFT JOIN `biblio_author` as biblio_author1 ON `biblio_author1`.`id`=`biblio_doc`.`author_name` LEFT JOIN `class_bibliography_type` as class_bibliography_type1 ON `class_bibliography_type1`.`id`=`biblio_doc`.`type` LEFT JOIN `class_bibliography_genre` as class_bibliography_genre1 ON `class_bibliography_genre1`.`id`=`biblio_doc`.`genre` LEFT JOIN `class_language` as class_language1 ON `class_language1`.`id`=`biblio_doc`.`language` LEFT JOIN `class_rights` as class_rights1 ON `class_rights1`.`id`=`biblio_doc`.`rights` LEFT JOIN `class_authority_library` as class_authority_library1 ON `class_authority_library1`.`id`=`biblio_doc`.`authority_organization` ',
				'filterers' => array('author' => 'author_name'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'transcript' => array(
				'parent_table' => 'biblio_trascript',
				'parent_pk_field' => 'id',
				'parent_caption' => 'IF(CHAR_LENGTH(`biblio_trascript`.`trascriber_memberID`) || CHAR_LENGTH(`biblio_trascript`.`transcript_title`), CONCAT_WS(\'\', `biblio_trascript`.`trascriber_memberID`, \'- \', `biblio_trascript`.`transcript_title`), \'\')',
				'parent_from' => '`biblio_trascript` LEFT JOIN `biblio_author` as biblio_author1 ON `biblio_author1`.`id`=`biblio_trascript`.`author` LEFT JOIN `biblio_doc` as biblio_doc1 ON `biblio_doc1`.`id`=`biblio_trascript`.`bibliography_title` ',
				'filterers' => array('author' => 'author', 'bibliography' => 'bibliography_id'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'token_sequence' => array(
				'parent_table' => 'biblio_token',
				'parent_pk_field' => 'id',
				'parent_caption' => '`biblio_token`.`token_sequence`',
				'parent_from' => '`biblio_token` LEFT JOIN `biblio_author` as biblio_author1 ON `biblio_author1`.`id`=`biblio_token`.`author` LEFT JOIN `biblio_doc` as biblio_doc1 ON `biblio_doc1`.`id`=`biblio_token`.`bibliography` LEFT JOIN `biblio_trascript` as biblio_trascript1 ON `biblio_trascript1`.`id`=`biblio_token`.`transcript` ',
				'filterers' => array('author' => 'author', 'bibliography' => 'bibliography', 'transcript' => 'transcript'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'token' => array(
				'parent_table' => 'biblio_token',
				'parent_pk_field' => 'id',
				'parent_caption' => '`biblio_token`.`token`',
				'parent_from' => '`biblio_token` LEFT JOIN `biblio_author` as biblio_author1 ON `biblio_author1`.`id`=`biblio_token`.`author` LEFT JOIN `biblio_doc` as biblio_doc1 ON `biblio_doc1`.`id`=`biblio_token`.`bibliography` LEFT JOIN `biblio_trascript` as biblio_trascript1 ON `biblio_trascript1`.`id`=`biblio_token`.`transcript` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			)
		),
		'code_herme' => array(   
			'author' => array(
				'parent_table' => 'biblio_author',
				'parent_pk_field' => 'id',
				'parent_caption' => 'IF(CHAR_LENGTH(`biblio_author`.`memberID`) || CHAR_LENGTH(`biblio_author`.`last_name`), CONCAT_WS(\'\', `biblio_author`.`memberID`, \'  \', `biblio_author`.`last_name`), \'\')',
				'parent_from' => '`biblio_author` LEFT JOIN `class_agent_type1` as class_agent_type11 ON `class_agent_type11`.`id`=`biblio_author`.`agenttype1` LEFT JOIN `class_agent_type2` as class_agent_type21 ON `class_agent_type21`.`id`=`biblio_author`.`agenttype2` LEFT JOIN `class_authority_agent` as class_authority_agent1 ON `class_authority_agent1`.`id`=`biblio_author`.`authority_organization` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'bibliography' => array(
				'parent_table' => 'biblio_doc',
				'parent_pk_field' => 'id',
				'parent_caption' => 'IF(CHAR_LENGTH(`biblio_doc`.`id`) || CHAR_LENGTH(`biblio_doc`.`title`), CONCAT_WS(\'\', `biblio_doc`.`id`, \'  \', `biblio_doc`.`title`), \'\')',
				'parent_from' => '`biblio_doc` LEFT JOIN `biblio_author` as biblio_author1 ON `biblio_author1`.`id`=`biblio_doc`.`author_name` LEFT JOIN `class_bibliography_type` as class_bibliography_type1 ON `class_bibliography_type1`.`id`=`biblio_doc`.`type` LEFT JOIN `class_bibliography_genre` as class_bibliography_genre1 ON `class_bibliography_genre1`.`id`=`biblio_doc`.`genre` LEFT JOIN `class_language` as class_language1 ON `class_language1`.`id`=`biblio_doc`.`language` LEFT JOIN `class_rights` as class_rights1 ON `class_rights1`.`id`=`biblio_doc`.`rights` LEFT JOIN `class_authority_library` as class_authority_library1 ON `class_authority_library1`.`id`=`biblio_doc`.`authority_organization` ',
				'filterers' => array('author' => 'author_name'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'transcript' => array(
				'parent_table' => 'biblio_trascript',
				'parent_pk_field' => 'id',
				'parent_caption' => 'IF(CHAR_LENGTH(`biblio_trascript`.`trascriber_memberID`) || CHAR_LENGTH(`biblio_trascript`.`transcript_title`), CONCAT_WS(\'\', `biblio_trascript`.`trascriber_memberID`, \' - \', `biblio_trascript`.`transcript_title`), \'\')',
				'parent_from' => '`biblio_trascript` LEFT JOIN `biblio_author` as biblio_author1 ON `biblio_author1`.`id`=`biblio_trascript`.`author` LEFT JOIN `biblio_doc` as biblio_doc1 ON `biblio_doc1`.`id`=`biblio_trascript`.`bibliography_title` ',
				'filterers' => array('author' => 'author', 'bibliography' => 'bibliography_id'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'token_sequence' => array(
				'parent_table' => 'biblio_token',
				'parent_pk_field' => 'id',
				'parent_caption' => '`biblio_token`.`token_sequence`',
				'parent_from' => '`biblio_token` LEFT JOIN `biblio_author` as biblio_author1 ON `biblio_author1`.`id`=`biblio_token`.`author` LEFT JOIN `biblio_doc` as biblio_doc1 ON `biblio_doc1`.`id`=`biblio_token`.`bibliography` LEFT JOIN `biblio_trascript` as biblio_trascript1 ON `biblio_trascript1`.`id`=`biblio_token`.`transcript` ',
				'filterers' => array('author' => 'author', 'bibliography' => 'bibliography', 'transcript' => 'transcript'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'token' => array(
				'parent_table' => 'biblio_token',
				'parent_pk_field' => 'id',
				'parent_caption' => 'IF(CHAR_LENGTH(`biblio_token`.`id`) || CHAR_LENGTH(`biblio_token`.`token`), CONCAT_WS(\'\', `biblio_token`.`id`, \'  \', `biblio_token`.`token`), \'\')',
				'parent_from' => '`biblio_token` LEFT JOIN `biblio_author` as biblio_author1 ON `biblio_author1`.`id`=`biblio_token`.`author` LEFT JOIN `biblio_doc` as biblio_doc1 ON `biblio_doc1`.`id`=`biblio_token`.`bibliography` LEFT JOIN `biblio_trascript` as biblio_trascript1 ON `biblio_trascript1`.`id`=`biblio_token`.`transcript` ',
				'filterers' => array('author' => 'author', 'bibliography' => 'bibliography', 'transcript' => 'transcript'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'impression' => array(
				'parent_table' => 'class_im',
				'parent_pk_field' => 'id',
				'parent_caption' => '`class_im`.`impression`',
				'parent_from' => '`class_im` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'noetictension' => array(
				'parent_table' => 'class_nt',
				'parent_pk_field' => 'id',
				'parent_caption' => '`class_nt`.`noetictension`',
				'parent_from' => '`class_nt` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			)
		),
		'code_chrev_scenes' => array(   
			'author' => array(
				'parent_table' => 'biblio_author',
				'parent_pk_field' => 'id',
				'parent_caption' => '`biblio_author`.`memberID`',
				'parent_from' => '`biblio_author` LEFT JOIN `class_agent_type1` as class_agent_type11 ON `class_agent_type11`.`id`=`biblio_author`.`agenttype1` LEFT JOIN `class_agent_type2` as class_agent_type21 ON `class_agent_type21`.`id`=`biblio_author`.`agenttype2` LEFT JOIN `class_authority_agent` as class_authority_agent1 ON `class_authority_agent1`.`id`=`biblio_author`.`authority_organization` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'bibliography' => array(
				'parent_table' => 'biblio_doc',
				'parent_pk_field' => 'id',
				'parent_caption' => 'IF(CHAR_LENGTH(`biblio_doc`.`id`) || CHAR_LENGTH(`biblio_doc`.`title`), CONCAT_WS(\'\', `biblio_doc`.`id`, \'  \', `biblio_doc`.`title`), \'\')',
				'parent_from' => '`biblio_doc` LEFT JOIN `biblio_author` as biblio_author1 ON `biblio_author1`.`id`=`biblio_doc`.`author_name` LEFT JOIN `class_bibliography_type` as class_bibliography_type1 ON `class_bibliography_type1`.`id`=`biblio_doc`.`type` LEFT JOIN `class_bibliography_genre` as class_bibliography_genre1 ON `class_bibliography_genre1`.`id`=`biblio_doc`.`genre` LEFT JOIN `class_language` as class_language1 ON `class_language1`.`id`=`biblio_doc`.`language` LEFT JOIN `class_rights` as class_rights1 ON `class_rights1`.`id`=`biblio_doc`.`rights` LEFT JOIN `class_authority_library` as class_authority_library1 ON `class_authority_library1`.`id`=`biblio_doc`.`authority_organization` ',
				'filterers' => array('author' => 'author_name'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'transcript' => array(
				'parent_table' => 'biblio_trascript',
				'parent_pk_field' => 'id',
				'parent_caption' => 'IF(CHAR_LENGTH(`biblio_trascript`.`trascriber_memberID`) || CHAR_LENGTH(`biblio_trascript`.`transcript_title`), CONCAT_WS(\'\', `biblio_trascript`.`trascriber_memberID`, \' - \', `biblio_trascript`.`transcript_title`), \'\')',
				'parent_from' => '`biblio_trascript` LEFT JOIN `biblio_author` as biblio_author1 ON `biblio_author1`.`id`=`biblio_trascript`.`author` LEFT JOIN `biblio_doc` as biblio_doc1 ON `biblio_doc1`.`id`=`biblio_trascript`.`bibliography_title` ',
				'filterers' => array('author' => 'author', 'bibliography' => 'bibliography_id'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'token_sequence' => array(
				'parent_table' => 'biblio_token',
				'parent_pk_field' => 'id',
				'parent_caption' => '`biblio_token`.`token_sequence`',
				'parent_from' => '`biblio_token` LEFT JOIN `biblio_author` as biblio_author1 ON `biblio_author1`.`id`=`biblio_token`.`author` LEFT JOIN `biblio_doc` as biblio_doc1 ON `biblio_doc1`.`id`=`biblio_token`.`bibliography` LEFT JOIN `biblio_trascript` as biblio_trascript1 ON `biblio_trascript1`.`id`=`biblio_token`.`transcript` ',
				'filterers' => array('author' => 'author', 'bibliography' => 'bibliography', 'transcript' => 'transcript'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'token' => array(
				'parent_table' => 'biblio_token',
				'parent_pk_field' => 'id',
				'parent_caption' => 'IF(CHAR_LENGTH(`biblio_token`.`token_sequence`) || CHAR_LENGTH(`biblio_token`.`token`), CONCAT_WS(\'\', `biblio_token`.`token_sequence`, \'  \', `biblio_token`.`token`), \'\')',
				'parent_from' => '`biblio_token` LEFT JOIN `biblio_author` as biblio_author1 ON `biblio_author1`.`id`=`biblio_token`.`author` LEFT JOIN `biblio_doc` as biblio_doc1 ON `biblio_doc1`.`id`=`biblio_token`.`bibliography` LEFT JOIN `biblio_trascript` as biblio_trascript1 ON `biblio_trascript1`.`id`=`biblio_token`.`transcript` ',
				'filterers' => array('author' => 'author', 'bibliography' => 'bibliography', 'transcript' => 'transcript'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'agent' => array(
				'parent_table' => 'biblio_author',
				'parent_pk_field' => 'id',
				'parent_caption' => '`biblio_author`.`memberID`',
				'parent_from' => '`biblio_author` LEFT JOIN `class_agent_type1` as class_agent_type11 ON `class_agent_type11`.`id`=`biblio_author`.`agenttype1` LEFT JOIN `class_agent_type2` as class_agent_type21 ON `class_agent_type21`.`id`=`biblio_author`.`agenttype2` LEFT JOIN `class_authority_agent` as class_authority_agent1 ON `class_authority_agent1`.`id`=`biblio_author`.`authority_organization` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'invivo_code' => array(
				'parent_table' => 'code_invivo',
				'parent_pk_field' => 'id',
				'parent_caption' => 'IF(CHAR_LENGTH(`code_invivo`.`id`) || CHAR_LENGTH(`code_invivo`.`token_sequence`), CONCAT_WS(\'\', `code_invivo`.`id`, \' / \', IF(    CHAR_LENGTH(`biblio_token1`.`token_sequence`), CONCAT_WS(\'\',   `biblio_token1`.`token_sequence`), \'\')), \'\')',
				'parent_from' => '`code_invivo` LEFT JOIN `biblio_author` as biblio_author1 ON `biblio_author1`.`id`=`code_invivo`.`author` LEFT JOIN `biblio_doc` as biblio_doc1 ON `biblio_doc1`.`id`=`code_invivo`.`bibliography` LEFT JOIN `biblio_trascript` as biblio_trascript1 ON `biblio_trascript1`.`id`=`code_invivo`.`transcript` LEFT JOIN `biblio_token` as biblio_token1 ON `biblio_token1`.`id`=`code_invivo`.`token_sequence` ',
				'filterers' => array('author' => 'author', 'bibliography' => 'bibliography', 'transcript' => 'transcript', 'token_sequence' => 'token_sequence'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'startdate' => array(
				'parent_table' => 'code_invivo',
				'parent_pk_field' => 'id',
				'parent_caption' => '`code_invivo`.`start_date`',
				'parent_from' => '`code_invivo` LEFT JOIN `biblio_author` as biblio_author1 ON `biblio_author1`.`id`=`code_invivo`.`author` LEFT JOIN `biblio_doc` as biblio_doc1 ON `biblio_doc1`.`id`=`code_invivo`.`bibliography` LEFT JOIN `biblio_trascript` as biblio_trascript1 ON `biblio_trascript1`.`id`=`code_invivo`.`transcript` LEFT JOIN `biblio_token` as biblio_token1 ON `biblio_token1`.`id`=`code_invivo`.`token_sequence` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'end_date' => array(
				'parent_table' => 'code_invivo',
				'parent_pk_field' => 'id',
				'parent_caption' => '`code_invivo`.`end_date`',
				'parent_from' => '`code_invivo` LEFT JOIN `biblio_author` as biblio_author1 ON `biblio_author1`.`id`=`code_invivo`.`author` LEFT JOIN `biblio_doc` as biblio_doc1 ON `biblio_doc1`.`id`=`code_invivo`.`bibliography` LEFT JOIN `biblio_trascript` as biblio_trascript1 ON `biblio_trascript1`.`id`=`code_invivo`.`transcript` LEFT JOIN `biblio_token` as biblio_token1 ON `biblio_token1`.`id`=`code_invivo`.`token_sequence` ',
				'filterers' => array('author' => 'author', 'bibliography' => 'bibliography', 'transcript' => 'transcript', 'token_sequence' => 'token_sequence'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'person' => array(
				'parent_table' => 'code_invivo',
				'parent_pk_field' => 'id',
				'parent_caption' => '`code_invivo`.`person`',
				'parent_from' => '`code_invivo` LEFT JOIN `biblio_author` as biblio_author1 ON `biblio_author1`.`id`=`code_invivo`.`author` LEFT JOIN `biblio_doc` as biblio_doc1 ON `biblio_doc1`.`id`=`code_invivo`.`bibliography` LEFT JOIN `biblio_trascript` as biblio_trascript1 ON `biblio_trascript1`.`id`=`code_invivo`.`transcript` LEFT JOIN `biblio_token` as biblio_token1 ON `biblio_token1`.`id`=`code_invivo`.`token_sequence` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'place' => array(
				'parent_table' => 'code_invivo',
				'parent_pk_field' => 'id',
				'parent_caption' => '`code_invivo`.`place`',
				'parent_from' => '`code_invivo` LEFT JOIN `biblio_author` as biblio_author1 ON `biblio_author1`.`id`=`code_invivo`.`author` LEFT JOIN `biblio_doc` as biblio_doc1 ON `biblio_doc1`.`id`=`code_invivo`.`bibliography` LEFT JOIN `biblio_trascript` as biblio_trascript1 ON `biblio_trascript1`.`id`=`code_invivo`.`transcript` LEFT JOIN `biblio_token` as biblio_token1 ON `biblio_token1`.`id`=`code_invivo`.`token_sequence` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'freecode' => array(
				'parent_table' => 'code_invivo',
				'parent_pk_field' => 'id',
				'parent_caption' => '`code_invivo`.`freecode`',
				'parent_from' => '`code_invivo` LEFT JOIN `biblio_author` as biblio_author1 ON `biblio_author1`.`id`=`code_invivo`.`author` LEFT JOIN `biblio_doc` as biblio_doc1 ON `biblio_doc1`.`id`=`code_invivo`.`bibliography` LEFT JOIN `biblio_trascript` as biblio_trascript1 ON `biblio_trascript1`.`id`=`code_invivo`.`transcript` LEFT JOIN `biblio_token` as biblio_token1 ON `biblio_token1`.`id`=`code_invivo`.`token_sequence` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'herme_code' => array(
				'parent_table' => 'code_herme',
				'parent_pk_field' => 'id',
				'parent_caption' => '`code_herme`.`id`',
				'parent_from' => '`code_herme` LEFT JOIN `biblio_author` as biblio_author1 ON `biblio_author1`.`id`=`code_herme`.`author` LEFT JOIN `biblio_doc` as biblio_doc1 ON `biblio_doc1`.`id`=`code_herme`.`bibliography` LEFT JOIN `biblio_trascript` as biblio_trascript1 ON `biblio_trascript1`.`id`=`code_herme`.`transcript` LEFT JOIN `biblio_token` as biblio_token1 ON `biblio_token1`.`id`=`code_herme`.`token_sequence` LEFT JOIN `class_im` as class_im1 ON `class_im1`.`id`=`code_herme`.`impression` LEFT JOIN `class_nt` as class_nt1 ON `class_nt1`.`id`=`code_herme`.`noetictension` ',
				'filterers' => array('author' => 'author', 'bibliography' => 'bibliography', 'transcript' => 'transcript', 'token_sequence' => 'token_sequence'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'impression' => array(
				'parent_table' => 'code_herme',
				'parent_pk_field' => 'id',
				'parent_caption' => 'IF(    CHAR_LENGTH(`class_im1`.`impression`), CONCAT_WS(\'\',   `class_im1`.`impression`), \'\')',
				'parent_from' => '`code_herme` LEFT JOIN `biblio_author` as biblio_author1 ON `biblio_author1`.`id`=`code_herme`.`author` LEFT JOIN `biblio_doc` as biblio_doc1 ON `biblio_doc1`.`id`=`code_herme`.`bibliography` LEFT JOIN `biblio_trascript` as biblio_trascript1 ON `biblio_trascript1`.`id`=`code_herme`.`transcript` LEFT JOIN `biblio_token` as biblio_token1 ON `biblio_token1`.`id`=`code_herme`.`token_sequence` LEFT JOIN `class_im` as class_im1 ON `class_im1`.`id`=`code_herme`.`impression` LEFT JOIN `class_nt` as class_nt1 ON `class_nt1`.`id`=`code_herme`.`noetictension` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'noetictension' => array(
				'parent_table' => 'code_herme',
				'parent_pk_field' => 'id',
				'parent_caption' => 'IF(    CHAR_LENGTH(`class_nt1`.`noetictension`), CONCAT_WS(\'\',   `class_nt1`.`noetictension`), \'\')',
				'parent_from' => '`code_herme` LEFT JOIN `biblio_author` as biblio_author1 ON `biblio_author1`.`id`=`code_herme`.`author` LEFT JOIN `biblio_doc` as biblio_doc1 ON `biblio_doc1`.`id`=`code_herme`.`bibliography` LEFT JOIN `biblio_trascript` as biblio_trascript1 ON `biblio_trascript1`.`id`=`code_herme`.`transcript` LEFT JOIN `biblio_token` as biblio_token1 ON `biblio_token1`.`id`=`code_herme`.`token_sequence` LEFT JOIN `class_im` as class_im1 ON `class_im1`.`id`=`code_herme`.`impression` LEFT JOIN `class_nt` as class_nt1 ON `class_nt1`.`id`=`code_herme`.`noetictension` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'comment' => array(
				'parent_table' => 'code_herme',
				'parent_pk_field' => 'id',
				'parent_caption' => '`code_herme`.`freecode`',
				'parent_from' => '`code_herme` LEFT JOIN `biblio_author` as biblio_author1 ON `biblio_author1`.`id`=`code_herme`.`author` LEFT JOIN `biblio_doc` as biblio_doc1 ON `biblio_doc1`.`id`=`code_herme`.`bibliography` LEFT JOIN `biblio_trascript` as biblio_trascript1 ON `biblio_trascript1`.`id`=`code_herme`.`transcript` LEFT JOIN `biblio_token` as biblio_token1 ON `biblio_token1`.`id`=`code_herme`.`token_sequence` LEFT JOIN `class_im` as class_im1 ON `class_im1`.`id`=`code_herme`.`impression` LEFT JOIN `class_nt` as class_nt1 ON `class_nt1`.`id`=`code_herme`.`noetictension` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'scene' => array(
				'parent_table' => 'code_encounter_scenes',
				'parent_pk_field' => 'id',
				'parent_caption' => '`code_encounter_scenes`.`scene`',
				'parent_from' => '`code_encounter_scenes` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			)
		),
		'code_character_development' => array(   
			'story' => array(
				'parent_table' => 'story',
				'parent_pk_field' => 'id',
				'parent_caption' => 'IF(CHAR_LENGTH(`story`.`id`) || CHAR_LENGTH(`story`.`story`), CONCAT_WS(\'\', `story`.`id`, \'  \', `story`.`story`), \'\')',
				'parent_from' => '`story` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'agent' => array(
				'parent_table' => 'story_characters',
				'parent_pk_field' => 'id',
				'parent_caption' => 'IF(    CHAR_LENGTH(`biblio_author1`.`last_name`) || CHAR_LENGTH(`biblio_author1`.`first_name`), CONCAT_WS(\'\',   `biblio_author1`.`last_name`, \', \', `biblio_author1`.`first_name`), \'\')',
				'parent_from' => '`story_characters` LEFT JOIN `story` as story1 ON `story1`.`id`=`story_characters`.`story` LEFT JOIN `class_dramatica_archetype` as class_dramatica_archetype1 ON `class_dramatica_archetype1`.`id`=`story_characters`.`role` LEFT JOIN `biblio_author` as biblio_author1 ON `biblio_author1`.`id`=`story_characters`.`agent_name` LEFT JOIN `class_nt` as class_nt1 ON `class_nt1`.`id`=`story_characters`.`noetictension` LEFT JOIN `class_im` as class_im1 ON `class_im1`.`id`=`story_characters`.`impression` ',
				'filterers' => array('story' => 'story'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'story_character' => array(
				'parent_table' => 'story_characters',
				'parent_pk_field' => 'id',
				'parent_caption' => 'IF(CHAR_LENGTH(`story_characters`.`role`) || CHAR_LENGTH(`story_characters`.`character`), CONCAT_WS(\'\', IF(    CHAR_LENGTH(`class_dramatica_archetype1`.`archetype`), CONCAT_WS(\'\',   `class_dramatica_archetype1`.`archetype`), \'\'), \'- \', `story_characters`.`character`), \'\')',
				'parent_from' => '`story_characters` LEFT JOIN `story` as story1 ON `story1`.`id`=`story_characters`.`story` LEFT JOIN `class_dramatica_archetype` as class_dramatica_archetype1 ON `class_dramatica_archetype1`.`id`=`story_characters`.`role` LEFT JOIN `biblio_author` as biblio_author1 ON `biblio_author1`.`id`=`story_characters`.`agent_name` LEFT JOIN `class_nt` as class_nt1 ON `class_nt1`.`id`=`story_characters`.`noetictension` LEFT JOIN `class_im` as class_im1 ON `class_im1`.`id`=`story_characters`.`impression` ',
				'filterers' => array('story' => 'story'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'author' => array(
				'parent_table' => 'biblio_author',
				'parent_pk_field' => 'id',
				'parent_caption' => 'IF(CHAR_LENGTH(`biblio_author`.`memberID`) || CHAR_LENGTH(`biblio_author`.`last_name`), CONCAT_WS(\'\', `biblio_author`.`memberID`, \' - \', `biblio_author`.`last_name`), \'\')',
				'parent_from' => '`biblio_author` LEFT JOIN `class_agent_type1` as class_agent_type11 ON `class_agent_type11`.`id`=`biblio_author`.`agenttype1` LEFT JOIN `class_agent_type2` as class_agent_type21 ON `class_agent_type21`.`id`=`biblio_author`.`agenttype2` LEFT JOIN `class_authority_agent` as class_authority_agent1 ON `class_authority_agent1`.`id`=`biblio_author`.`authority_organization` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'bibliography' => array(
				'parent_table' => 'biblio_doc',
				'parent_pk_field' => 'id',
				'parent_caption' => 'IF(CHAR_LENGTH(`biblio_doc`.`id`) || CHAR_LENGTH(`biblio_doc`.`title`), CONCAT_WS(\'\', `biblio_doc`.`id`, \'  \', `biblio_doc`.`title`), \'\')',
				'parent_from' => '`biblio_doc` LEFT JOIN `biblio_author` as biblio_author1 ON `biblio_author1`.`id`=`biblio_doc`.`author_name` LEFT JOIN `class_bibliography_type` as class_bibliography_type1 ON `class_bibliography_type1`.`id`=`biblio_doc`.`type` LEFT JOIN `class_bibliography_genre` as class_bibliography_genre1 ON `class_bibliography_genre1`.`id`=`biblio_doc`.`genre` LEFT JOIN `class_language` as class_language1 ON `class_language1`.`id`=`biblio_doc`.`language` LEFT JOIN `class_rights` as class_rights1 ON `class_rights1`.`id`=`biblio_doc`.`rights` LEFT JOIN `class_authority_library` as class_authority_library1 ON `class_authority_library1`.`id`=`biblio_doc`.`authority_organization` ',
				'filterers' => array('author' => 'author_name'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'transcript' => array(
				'parent_table' => 'biblio_trascript',
				'parent_pk_field' => 'id',
				'parent_caption' => 'IF(CHAR_LENGTH(`biblio_trascript`.`trascriber_memberID`) || CHAR_LENGTH(`biblio_trascript`.`transcript_title`), CONCAT_WS(\'\', `biblio_trascript`.`trascriber_memberID`, \' - \', `biblio_trascript`.`transcript_title`), \'\')',
				'parent_from' => '`biblio_trascript` LEFT JOIN `biblio_author` as biblio_author1 ON `biblio_author1`.`id`=`biblio_trascript`.`author` LEFT JOIN `biblio_doc` as biblio_doc1 ON `biblio_doc1`.`id`=`biblio_trascript`.`bibliography_title` ',
				'filterers' => array('author' => 'author', 'bibliography' => 'bibliography_id'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'token_sequence' => array(
				'parent_table' => 'biblio_token',
				'parent_pk_field' => 'id',
				'parent_caption' => '`biblio_token`.`id`',
				'parent_from' => '`biblio_token` LEFT JOIN `biblio_author` as biblio_author1 ON `biblio_author1`.`id`=`biblio_token`.`author` LEFT JOIN `biblio_doc` as biblio_doc1 ON `biblio_doc1`.`id`=`biblio_token`.`bibliography` LEFT JOIN `biblio_trascript` as biblio_trascript1 ON `biblio_trascript1`.`id`=`biblio_token`.`transcript` ',
				'filterers' => array('author' => 'author', 'bibliography' => 'bibliography', 'transcript' => 'transcript'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'token' => array(
				'parent_table' => 'biblio_token',
				'parent_pk_field' => 'id',
				'parent_caption' => '`biblio_token`.`token`',
				'parent_from' => '`biblio_token` LEFT JOIN `biblio_author` as biblio_author1 ON `biblio_author1`.`id`=`biblio_token`.`author` LEFT JOIN `biblio_doc` as biblio_doc1 ON `biblio_doc1`.`id`=`biblio_token`.`bibliography` LEFT JOIN `biblio_trascript` as biblio_trascript1 ON `biblio_trascript1`.`id`=`biblio_token`.`transcript` ',
				'filterers' => array('author' => 'author', 'bibliography' => 'bibliography', 'transcript' => 'transcript'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'code' => array(
				'parent_table' => 'code_herme',
				'parent_pk_field' => 'id',
				'parent_caption' => '`code_herme`.`freecode`',
				'parent_from' => '`code_herme` LEFT JOIN `biblio_author` as biblio_author1 ON `biblio_author1`.`id`=`code_herme`.`author` LEFT JOIN `biblio_doc` as biblio_doc1 ON `biblio_doc1`.`id`=`code_herme`.`bibliography` LEFT JOIN `biblio_trascript` as biblio_trascript1 ON `biblio_trascript1`.`id`=`code_herme`.`transcript` LEFT JOIN `biblio_token` as biblio_token1 ON `biblio_token1`.`id`=`code_herme`.`token_sequence` LEFT JOIN `class_im` as class_im1 ON `class_im1`.`id`=`code_herme`.`impression` LEFT JOIN `class_nt` as class_nt1 ON `class_nt1`.`id`=`code_herme`.`noetictension` ',
				'filterers' => array('author' => 'author', 'bibliography' => 'bibliography', 'transcript' => 'transcript', 'token' => 'token_sequence'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'character_element' => array(
				'parent_table' => 'class_character_element',
				'parent_pk_field' => 'id',
				'parent_caption' => '`class_character_element`.`element`',
				'parent_from' => '`class_character_element` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			)
		),
		'code_encounters' => array(   
			'agentA' => array(
				'parent_table' => 'biblio_author',
				'parent_pk_field' => 'id',
				'parent_caption' => '`biblio_author`.`memberID`',
				'parent_from' => '`biblio_author` LEFT JOIN `class_agent_type1` as class_agent_type11 ON `class_agent_type11`.`id`=`biblio_author`.`agenttype1` LEFT JOIN `class_agent_type2` as class_agent_type21 ON `class_agent_type21`.`id`=`biblio_author`.`agenttype2` LEFT JOIN `class_authority_agent` as class_authority_agent1 ON `class_authority_agent1`.`id`=`biblio_author`.`authority_organization` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'authorA' => array(
				'parent_table' => 'biblio_author',
				'parent_pk_field' => 'id',
				'parent_caption' => '`biblio_author`.`memberID`',
				'parent_from' => '`biblio_author` LEFT JOIN `class_agent_type1` as class_agent_type11 ON `class_agent_type11`.`id`=`biblio_author`.`agenttype1` LEFT JOIN `class_agent_type2` as class_agent_type21 ON `class_agent_type21`.`id`=`biblio_author`.`agenttype2` LEFT JOIN `class_authority_agent` as class_authority_agent1 ON `class_authority_agent1`.`id`=`biblio_author`.`authority_organization` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'bibliographyA' => array(
				'parent_table' => 'biblio_doc',
				'parent_pk_field' => 'id',
				'parent_caption' => 'IF(CHAR_LENGTH(`biblio_doc`.`id`) || CHAR_LENGTH(`biblio_doc`.`title`), CONCAT_WS(\'\', `biblio_doc`.`id`, \'  \', `biblio_doc`.`title`), \'\')',
				'parent_from' => '`biblio_doc` LEFT JOIN `biblio_author` as biblio_author1 ON `biblio_author1`.`id`=`biblio_doc`.`author_name` LEFT JOIN `class_bibliography_type` as class_bibliography_type1 ON `class_bibliography_type1`.`id`=`biblio_doc`.`type` LEFT JOIN `class_bibliography_genre` as class_bibliography_genre1 ON `class_bibliography_genre1`.`id`=`biblio_doc`.`genre` LEFT JOIN `class_language` as class_language1 ON `class_language1`.`id`=`biblio_doc`.`language` LEFT JOIN `class_rights` as class_rights1 ON `class_rights1`.`id`=`biblio_doc`.`rights` LEFT JOIN `class_authority_library` as class_authority_library1 ON `class_authority_library1`.`id`=`biblio_doc`.`authority_organization` ',
				'filterers' => array('authorA' => 'author_name'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'transcriptA' => array(
				'parent_table' => 'biblio_trascript',
				'parent_pk_field' => 'id',
				'parent_caption' => 'IF(CHAR_LENGTH(`biblio_trascript`.`trascriber_memberID`) || CHAR_LENGTH(`biblio_trascript`.`transcript_title`), CONCAT_WS(\'\', `biblio_trascript`.`trascriber_memberID`, \' - \', `biblio_trascript`.`transcript_title`), \'\')',
				'parent_from' => '`biblio_trascript` LEFT JOIN `biblio_author` as biblio_author1 ON `biblio_author1`.`id`=`biblio_trascript`.`author` LEFT JOIN `biblio_doc` as biblio_doc1 ON `biblio_doc1`.`id`=`biblio_trascript`.`bibliography_title` ',
				'filterers' => array('authorA' => 'author', 'bibliographyA' => 'bibliography_id'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'tokenA' => array(
				'parent_table' => 'biblio_token',
				'parent_pk_field' => 'id',
				'parent_caption' => 'IF(CHAR_LENGTH(`biblio_token`.`token_sequence`) || CHAR_LENGTH(`biblio_token`.`token`), CONCAT_WS(\'\', `biblio_token`.`token_sequence`, \'  \', `biblio_token`.`token`), \'\')',
				'parent_from' => '`biblio_token` LEFT JOIN `biblio_author` as biblio_author1 ON `biblio_author1`.`id`=`biblio_token`.`author` LEFT JOIN `biblio_doc` as biblio_doc1 ON `biblio_doc1`.`id`=`biblio_token`.`bibliography` LEFT JOIN `biblio_trascript` as biblio_trascript1 ON `biblio_trascript1`.`id`=`biblio_token`.`transcript` ',
				'filterers' => array('authorA' => 'author', 'bibliographyA' => 'bibliography', 'transcriptA' => 'transcript'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'sceneA' => array(
				'parent_table' => 'code_encounter_scenes',
				'parent_pk_field' => 'id',
				'parent_caption' => '`code_encounter_scenes`.`scene`',
				'parent_from' => '`code_encounter_scenes` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'agentB' => array(
				'parent_table' => 'biblio_author',
				'parent_pk_field' => 'id',
				'parent_caption' => '`biblio_author`.`memberID`',
				'parent_from' => '`biblio_author` LEFT JOIN `class_agent_type1` as class_agent_type11 ON `class_agent_type11`.`id`=`biblio_author`.`agenttype1` LEFT JOIN `class_agent_type2` as class_agent_type21 ON `class_agent_type21`.`id`=`biblio_author`.`agenttype2` LEFT JOIN `class_authority_agent` as class_authority_agent1 ON `class_authority_agent1`.`id`=`biblio_author`.`authority_organization` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'authorB' => array(
				'parent_table' => 'biblio_author',
				'parent_pk_field' => 'id',
				'parent_caption' => '`biblio_author`.`memberID`',
				'parent_from' => '`biblio_author` LEFT JOIN `class_agent_type1` as class_agent_type11 ON `class_agent_type11`.`id`=`biblio_author`.`agenttype1` LEFT JOIN `class_agent_type2` as class_agent_type21 ON `class_agent_type21`.`id`=`biblio_author`.`agenttype2` LEFT JOIN `class_authority_agent` as class_authority_agent1 ON `class_authority_agent1`.`id`=`biblio_author`.`authority_organization` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'bibliographyB' => array(
				'parent_table' => 'biblio_doc',
				'parent_pk_field' => 'id',
				'parent_caption' => 'IF(CHAR_LENGTH(`biblio_doc`.`id`) || CHAR_LENGTH(`biblio_doc`.`title`), CONCAT_WS(\'\', `biblio_doc`.`id`, \'  \', `biblio_doc`.`title`), \'\')',
				'parent_from' => '`biblio_doc` LEFT JOIN `biblio_author` as biblio_author1 ON `biblio_author1`.`id`=`biblio_doc`.`author_name` LEFT JOIN `class_bibliography_type` as class_bibliography_type1 ON `class_bibliography_type1`.`id`=`biblio_doc`.`type` LEFT JOIN `class_bibliography_genre` as class_bibliography_genre1 ON `class_bibliography_genre1`.`id`=`biblio_doc`.`genre` LEFT JOIN `class_language` as class_language1 ON `class_language1`.`id`=`biblio_doc`.`language` LEFT JOIN `class_rights` as class_rights1 ON `class_rights1`.`id`=`biblio_doc`.`rights` LEFT JOIN `class_authority_library` as class_authority_library1 ON `class_authority_library1`.`id`=`biblio_doc`.`authority_organization` ',
				'filterers' => array('authorB' => 'author_name'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'transcriptB' => array(
				'parent_table' => 'biblio_trascript',
				'parent_pk_field' => 'id',
				'parent_caption' => 'IF(CHAR_LENGTH(`biblio_trascript`.`trascriber_memberID`) || CHAR_LENGTH(`biblio_trascript`.`transcript_title`), CONCAT_WS(\'\', `biblio_trascript`.`trascriber_memberID`, \' - \', `biblio_trascript`.`transcript_title`), \'\')',
				'parent_from' => '`biblio_trascript` LEFT JOIN `biblio_author` as biblio_author1 ON `biblio_author1`.`id`=`biblio_trascript`.`author` LEFT JOIN `biblio_doc` as biblio_doc1 ON `biblio_doc1`.`id`=`biblio_trascript`.`bibliography_title` ',
				'filterers' => array('authorB' => 'author', 'bibliographyB' => 'bibliography_id'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'tokenB' => array(
				'parent_table' => 'biblio_token',
				'parent_pk_field' => 'id',
				'parent_caption' => 'IF(CHAR_LENGTH(`biblio_token`.`id`) || CHAR_LENGTH(`biblio_token`.`token`), CONCAT_WS(\'\', `biblio_token`.`id`, \'  \', `biblio_token`.`token`), \'\')',
				'parent_from' => '`biblio_token` LEFT JOIN `biblio_author` as biblio_author1 ON `biblio_author1`.`id`=`biblio_token`.`author` LEFT JOIN `biblio_doc` as biblio_doc1 ON `biblio_doc1`.`id`=`biblio_token`.`bibliography` LEFT JOIN `biblio_trascript` as biblio_trascript1 ON `biblio_trascript1`.`id`=`biblio_token`.`transcript` ',
				'filterers' => array('authorB' => 'author', 'bibliographyB' => 'bibliography'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'sceneB' => array(
				'parent_table' => 'code_encounter_scenes',
				'parent_pk_field' => 'id',
				'parent_caption' => 'IF(CHAR_LENGTH(`code_encounter_scenes`.`scene`), CONCAT_WS(\'\', `code_encounter_scenes`.`scene`, \'  \'), \'\')',
				'parent_from' => '`code_encounter_scenes` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'story_scene' => array(
				'parent_table' => 'code_encounter_scenes',
				'parent_pk_field' => 'id',
				'parent_caption' => '`code_encounter_scenes`.`scene`',
				'parent_from' => '`code_encounter_scenes` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			)
		),
		'code_encounter_scenes' => array(  
		),
		'story' => array(  
		),
		'story_characters' => array(   
			'story' => array(
				'parent_table' => 'story',
				'parent_pk_field' => 'id',
				'parent_caption' => 'IF(CHAR_LENGTH(`story`.`id`) || CHAR_LENGTH(`story`.`story`), CONCAT_WS(\'\', `story`.`id`, \'  \', `story`.`story`), \'\')',
				'parent_from' => '`story` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'role' => array(
				'parent_table' => 'class_dramatica_archetype',
				'parent_pk_field' => 'id',
				'parent_caption' => '`class_dramatica_archetype`.`archetype`',
				'parent_from' => '`class_dramatica_archetype` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'memberID' => array(
				'parent_table' => 'biblio_author',
				'parent_pk_field' => 'id',
				'parent_caption' => '`biblio_author`.`memberID`',
				'parent_from' => '`biblio_author` LEFT JOIN `class_agent_type1` as class_agent_type11 ON `class_agent_type11`.`id`=`biblio_author`.`agenttype1` LEFT JOIN `class_agent_type2` as class_agent_type21 ON `class_agent_type21`.`id`=`biblio_author`.`agenttype2` LEFT JOIN `class_authority_agent` as class_authority_agent1 ON `class_authority_agent1`.`id`=`biblio_author`.`authority_organization` ',
				'filterers' => array(),
				'custom_query' => 'SELECT `membership_users`.`memberID`, `membership_users`.`memberID` FROM `membership_users` LEFT JOIN `class_authority_agent` as class_authority_agent1 ON `class_authority_agent1`.`id`=`membership_users`.`authority_organization` ORDER BY 2',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'agent_name' => array(
				'parent_table' => 'biblio_author',
				'parent_pk_field' => 'id',
				'parent_caption' => 'IF(CHAR_LENGTH(`biblio_author`.`last_name`) || CHAR_LENGTH(`biblio_author`.`first_name`), CONCAT_WS(\'\', `biblio_author`.`last_name`, \', \', `biblio_author`.`first_name`), \'\')',
				'parent_from' => '`biblio_author` LEFT JOIN `class_agent_type1` as class_agent_type11 ON `class_agent_type11`.`id`=`biblio_author`.`agenttype1` LEFT JOIN `class_agent_type2` as class_agent_type21 ON `class_agent_type21`.`id`=`biblio_author`.`agenttype2` LEFT JOIN `class_authority_agent` as class_authority_agent1 ON `class_authority_agent1`.`id`=`biblio_author`.`authority_organization` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'img' => array(
				'parent_table' => 'biblio_author',
				'parent_pk_field' => 'id',
				'parent_caption' => '`biblio_author`.`img`',
				'parent_from' => '`biblio_author` LEFT JOIN `class_agent_type1` as class_agent_type11 ON `class_agent_type11`.`id`=`biblio_author`.`agenttype1` LEFT JOIN `class_agent_type2` as class_agent_type21 ON `class_agent_type21`.`id`=`biblio_author`.`agenttype2` LEFT JOIN `class_authority_agent` as class_authority_agent1 ON `class_authority_agent1`.`id`=`biblio_author`.`authority_organization` ',
				'filterers' => array(),
				'custom_query' => 'SELECT `membership_users`.`memberID`, `membership_users`.`img` FROM `membership_users` LEFT JOIN `class_authority_agent` as class_authority_agent1 ON `class_authority_agent1`.`id`=`membership_users`.`authority_organization` ORDER BY 2',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'noetictension' => array(
				'parent_table' => 'class_nt',
				'parent_pk_field' => 'id',
				'parent_caption' => '`class_nt`.`noetictension`',
				'parent_from' => '`class_nt` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'impression' => array(
				'parent_table' => 'class_im',
				'parent_pk_field' => 'id',
				'parent_caption' => '`class_im`.`impression`',
				'parent_from' => '`class_im` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			)
		),
		'storypoints_static' => array(   
			'story' => array(
				'parent_table' => 'story',
				'parent_pk_field' => 'id',
				'parent_caption' => 'IF(CHAR_LENGTH(`story`.`id`) || CHAR_LENGTH(`story`.`story`), CONCAT_WS(\'\', `story`.`id`, \'  \', `story`.`story`), \'\')',
				'parent_from' => '`story` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'throughline' => array(
				'parent_table' => 'class_dramatica_throughline',
				'parent_pk_field' => 'id',
				'parent_caption' => '`class_dramatica_throughline`.`throughline`',
				'parent_from' => '`class_dramatica_throughline` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'throughline_domain' => array(
				'parent_table' => 'class_dramatica_domain',
				'parent_pk_field' => 'id',
				'parent_caption' => '`class_dramatica_domain`.`domain`',
				'parent_from' => '`class_dramatica_domain` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'concern' => array(
				'parent_table' => 'class_dramatica_concern',
				'parent_pk_field' => 'id',
				'parent_caption' => '`class_dramatica_concern`.`concern`',
				'parent_from' => '`class_dramatica_concern` LEFT JOIN `class_dramatica_domain` as class_dramatica_domain1 ON `class_dramatica_domain1`.`id`=`class_dramatica_concern`.`domain` ',
				'filterers' => array('throughline_domain' => 'domain'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'issue' => array(
				'parent_table' => 'class_dramatica_issue',
				'parent_pk_field' => 'id',
				'parent_caption' => '`class_dramatica_issue`.`issue`',
				'parent_from' => '`class_dramatica_issue` LEFT JOIN `class_dramatica_domain` as class_dramatica_domain1 ON `class_dramatica_domain1`.`id`=`class_dramatica_issue`.`domain` LEFT JOIN `class_dramatica_concern` as class_dramatica_concern1 ON `class_dramatica_concern1`.`id`=`class_dramatica_issue`.`concern` ',
				'filterers' => array('throughline_domain' => 'domain', 'concern' => 'concern'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'problem' => array(
				'parent_table' => 'class_dramatica_themes',
				'parent_pk_field' => 'id',
				'parent_caption' => '`class_dramatica_themes`.`theme`',
				'parent_from' => '`class_dramatica_themes` LEFT JOIN `class_dramatica_domain` as class_dramatica_domain1 ON `class_dramatica_domain1`.`id`=`class_dramatica_themes`.`domain` LEFT JOIN `class_dramatica_concern` as class_dramatica_concern1 ON `class_dramatica_concern1`.`id`=`class_dramatica_themes`.`concern` LEFT JOIN `class_dramatica_issue` as class_dramatica_issue1 ON `class_dramatica_issue1`.`id`=`class_dramatica_themes`.`issue` ',
				'filterers' => array('throughline_domain' => 'domain', 'concern' => 'concern', 'issue' => 'issue'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'solution' => array(
				'parent_table' => 'class_dramatica_themes',
				'parent_pk_field' => 'id',
				'parent_caption' => '`class_dramatica_themes`.`theme`',
				'parent_from' => '`class_dramatica_themes` LEFT JOIN `class_dramatica_domain` as class_dramatica_domain1 ON `class_dramatica_domain1`.`id`=`class_dramatica_themes`.`domain` LEFT JOIN `class_dramatica_concern` as class_dramatica_concern1 ON `class_dramatica_concern1`.`id`=`class_dramatica_themes`.`concern` LEFT JOIN `class_dramatica_issue` as class_dramatica_issue1 ON `class_dramatica_issue1`.`id`=`class_dramatica_themes`.`issue` ',
				'filterers' => array('throughline_domain' => 'domain', 'concern' => 'concern', 'issue' => 'issue'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'symptom' => array(
				'parent_table' => 'class_dramatica_themes',
				'parent_pk_field' => 'id',
				'parent_caption' => '`class_dramatica_themes`.`theme`',
				'parent_from' => '`class_dramatica_themes` LEFT JOIN `class_dramatica_domain` as class_dramatica_domain1 ON `class_dramatica_domain1`.`id`=`class_dramatica_themes`.`domain` LEFT JOIN `class_dramatica_concern` as class_dramatica_concern1 ON `class_dramatica_concern1`.`id`=`class_dramatica_themes`.`concern` LEFT JOIN `class_dramatica_issue` as class_dramatica_issue1 ON `class_dramatica_issue1`.`id`=`class_dramatica_themes`.`issue` ',
				'filterers' => array('throughline_domain' => 'domain', 'concern' => 'concern', 'issue' => 'issue'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'response' => array(
				'parent_table' => 'class_dramatica_themes',
				'parent_pk_field' => 'id',
				'parent_caption' => '`class_dramatica_themes`.`theme`',
				'parent_from' => '`class_dramatica_themes` LEFT JOIN `class_dramatica_domain` as class_dramatica_domain1 ON `class_dramatica_domain1`.`id`=`class_dramatica_themes`.`domain` LEFT JOIN `class_dramatica_concern` as class_dramatica_concern1 ON `class_dramatica_concern1`.`id`=`class_dramatica_themes`.`concern` LEFT JOIN `class_dramatica_issue` as class_dramatica_issue1 ON `class_dramatica_issue1`.`id`=`class_dramatica_themes`.`issue` ',
				'filterers' => array('throughline_domain' => 'domain', 'concern' => 'concern', 'issue' => 'issue'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'catalyst' => array(
				'parent_table' => 'class_dramatica_issue',
				'parent_pk_field' => 'id',
				'parent_caption' => '`class_dramatica_issue`.`issue`',
				'parent_from' => '`class_dramatica_issue` LEFT JOIN `class_dramatica_domain` as class_dramatica_domain1 ON `class_dramatica_domain1`.`id`=`class_dramatica_issue`.`domain` LEFT JOIN `class_dramatica_concern` as class_dramatica_concern1 ON `class_dramatica_concern1`.`id`=`class_dramatica_issue`.`concern` ',
				'filterers' => array('throughline_domain' => 'domain', 'concern' => 'concern'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'inhibitor' => array(
				'parent_table' => 'class_dramatica_issue',
				'parent_pk_field' => 'id',
				'parent_caption' => '`class_dramatica_issue`.`issue`',
				'parent_from' => '`class_dramatica_issue` LEFT JOIN `class_dramatica_domain` as class_dramatica_domain1 ON `class_dramatica_domain1`.`id`=`class_dramatica_issue`.`domain` LEFT JOIN `class_dramatica_concern` as class_dramatica_concern1 ON `class_dramatica_concern1`.`id`=`class_dramatica_issue`.`concern` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'benchmark' => array(
				'parent_table' => 'class_dramatica_concern',
				'parent_pk_field' => 'id',
				'parent_caption' => '`class_dramatica_concern`.`concern`',
				'parent_from' => '`class_dramatica_concern` LEFT JOIN `class_dramatica_domain` as class_dramatica_domain1 ON `class_dramatica_domain1`.`id`=`class_dramatica_concern`.`domain` ',
				'filterers' => array('throughline_domain' => 'domain'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			)
		),
		'storydynamic' => array(   
			'story' => array(
				'parent_table' => 'story',
				'parent_pk_field' => 'id',
				'parent_caption' => 'IF(CHAR_LENGTH(`story`.`id`) || CHAR_LENGTH(`story`.`story`), CONCAT_WS(\'\', `story`.`id`, \'  \', `story`.`story`), \'\')',
				'parent_from' => '`story` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'OS_goal_domain' => array(
				'parent_table' => 'class_dramatica_domain',
				'parent_pk_field' => 'id',
				'parent_caption' => '`class_dramatica_domain`.`domain`',
				'parent_from' => '`class_dramatica_domain` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'OS_goal_concern' => array(
				'parent_table' => 'class_dramatica_concern',
				'parent_pk_field' => 'id',
				'parent_caption' => '`class_dramatica_concern`.`concern`',
				'parent_from' => '`class_dramatica_concern` LEFT JOIN `class_dramatica_domain` as class_dramatica_domain1 ON `class_dramatica_domain1`.`id`=`class_dramatica_concern`.`domain` ',
				'filterers' => array('OS_goal_domain' => 'domain'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'OS_consequence_domain' => array(
				'parent_table' => 'class_dramatica_domain',
				'parent_pk_field' => 'id',
				'parent_caption' => '`class_dramatica_domain`.`domain`',
				'parent_from' => '`class_dramatica_domain` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'OS_consequence_concern' => array(
				'parent_table' => 'class_dramatica_concern',
				'parent_pk_field' => 'id',
				'parent_caption' => '`class_dramatica_concern`.`concern`',
				'parent_from' => '`class_dramatica_concern` LEFT JOIN `class_dramatica_domain` as class_dramatica_domain1 ON `class_dramatica_domain1`.`id`=`class_dramatica_concern`.`domain` ',
				'filterers' => array('OS_consequence_domain' => 'domain'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'OS_cost_domain' => array(
				'parent_table' => 'class_dramatica_domain',
				'parent_pk_field' => 'id',
				'parent_caption' => '`class_dramatica_domain`.`domain`',
				'parent_from' => '`class_dramatica_domain` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'OS_cost_concern' => array(
				'parent_table' => 'class_dramatica_concern',
				'parent_pk_field' => 'id',
				'parent_caption' => '`class_dramatica_concern`.`concern`',
				'parent_from' => '`class_dramatica_concern` LEFT JOIN `class_dramatica_domain` as class_dramatica_domain1 ON `class_dramatica_domain1`.`id`=`class_dramatica_concern`.`domain` ',
				'filterers' => array('OS_cost_domain' => 'domain'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'OS_dividend_domain' => array(
				'parent_table' => 'class_dramatica_domain',
				'parent_pk_field' => 'id',
				'parent_caption' => '`class_dramatica_domain`.`domain`',
				'parent_from' => '`class_dramatica_domain` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'OS_dividend_concern' => array(
				'parent_table' => 'class_dramatica_concern',
				'parent_pk_field' => 'id',
				'parent_caption' => '`class_dramatica_concern`.`concern`',
				'parent_from' => '`class_dramatica_concern` LEFT JOIN `class_dramatica_domain` as class_dramatica_domain1 ON `class_dramatica_domain1`.`id`=`class_dramatica_concern`.`domain` ',
				'filterers' => array('OS_dividend_domain' => 'domain'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'OS_requirements_domain' => array(
				'parent_table' => 'class_dramatica_domain',
				'parent_pk_field' => 'id',
				'parent_caption' => '`class_dramatica_domain`.`domain`',
				'parent_from' => '`class_dramatica_domain` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'OS_requirements_concern' => array(
				'parent_table' => 'class_dramatica_concern',
				'parent_pk_field' => 'id',
				'parent_caption' => '`class_dramatica_concern`.`concern`',
				'parent_from' => '`class_dramatica_concern` LEFT JOIN `class_dramatica_domain` as class_dramatica_domain1 ON `class_dramatica_domain1`.`id`=`class_dramatica_concern`.`domain` ',
				'filterers' => array('OS_requirements_domain' => 'domain'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'OS_prerequesites_domain' => array(
				'parent_table' => 'class_dramatica_domain',
				'parent_pk_field' => 'id',
				'parent_caption' => '`class_dramatica_domain`.`domain`',
				'parent_from' => '`class_dramatica_domain` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'OS_prerequesites_concern' => array(
				'parent_table' => 'class_dramatica_concern',
				'parent_pk_field' => 'id',
				'parent_caption' => '`class_dramatica_concern`.`concern`',
				'parent_from' => '`class_dramatica_concern` LEFT JOIN `class_dramatica_domain` as class_dramatica_domain1 ON `class_dramatica_domain1`.`id`=`class_dramatica_concern`.`domain` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'OS_preconditions_domain' => array(
				'parent_table' => 'class_dramatica_domain',
				'parent_pk_field' => 'id',
				'parent_caption' => '`class_dramatica_domain`.`domain`',
				'parent_from' => '`class_dramatica_domain` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'OS_preconditions_concern' => array(
				'parent_table' => 'class_dramatica_concern',
				'parent_pk_field' => 'id',
				'parent_caption' => '`class_dramatica_concern`.`concern`',
				'parent_from' => '`class_dramatica_concern` LEFT JOIN `class_dramatica_domain` as class_dramatica_domain1 ON `class_dramatica_domain1`.`id`=`class_dramatica_concern`.`domain` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'OS_forewarnings_domain' => array(
				'parent_table' => 'class_dramatica_domain',
				'parent_pk_field' => 'id',
				'parent_caption' => '`class_dramatica_domain`.`domain`',
				'parent_from' => '`class_dramatica_domain` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'OS_forewarnings_concern' => array(
				'parent_table' => 'class_dramatica_concern',
				'parent_pk_field' => 'id',
				'parent_caption' => '`class_dramatica_concern`.`concern`',
				'parent_from' => '`class_dramatica_concern` LEFT JOIN `class_dramatica_domain` as class_dramatica_domain1 ON `class_dramatica_domain1`.`id`=`class_dramatica_concern`.`domain` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			)
		),
		'storyweaving_scenes' => array(   
			'story' => array(
				'parent_table' => 'story',
				'parent_pk_field' => 'id',
				'parent_caption' => 'IF(CHAR_LENGTH(`story`.`id`) || CHAR_LENGTH(`story`.`story`), CONCAT_WS(\'\', `story`.`id`, \'  \', `story`.`story`), \'\')',
				'parent_from' => '`story` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'throughline' => array(
				'parent_table' => 'class_dramatica_throughline',
				'parent_pk_field' => 'id',
				'parent_caption' => '`class_dramatica_throughline`.`throughline`',
				'parent_from' => '`class_dramatica_throughline` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'domain' => array(
				'parent_table' => 'class_dramatica_domain',
				'parent_pk_field' => 'id',
				'parent_caption' => '`class_dramatica_domain`.`domain`',
				'parent_from' => '`class_dramatica_domain` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'concern' => array(
				'parent_table' => 'class_dramatica_concern',
				'parent_pk_field' => 'id',
				'parent_caption' => '`class_dramatica_concern`.`concern`',
				'parent_from' => '`class_dramatica_concern` LEFT JOIN `class_dramatica_domain` as class_dramatica_domain1 ON `class_dramatica_domain1`.`id`=`class_dramatica_concern`.`domain` ',
				'filterers' => array('domain' => 'domain'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'issue' => array(
				'parent_table' => 'class_dramatica_issue',
				'parent_pk_field' => 'id',
				'parent_caption' => '`class_dramatica_issue`.`issue`',
				'parent_from' => '`class_dramatica_issue` LEFT JOIN `class_dramatica_domain` as class_dramatica_domain1 ON `class_dramatica_domain1`.`id`=`class_dramatica_issue`.`domain` LEFT JOIN `class_dramatica_concern` as class_dramatica_concern1 ON `class_dramatica_concern1`.`id`=`class_dramatica_issue`.`concern` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'theme' => array(
				'parent_table' => 'class_dramatica_themes',
				'parent_pk_field' => 'id',
				'parent_caption' => '`class_dramatica_themes`.`theme`',
				'parent_from' => '`class_dramatica_themes` LEFT JOIN `class_dramatica_domain` as class_dramatica_domain1 ON `class_dramatica_domain1`.`id`=`class_dramatica_themes`.`domain` LEFT JOIN `class_dramatica_concern` as class_dramatica_concern1 ON `class_dramatica_concern1`.`id`=`class_dramatica_themes`.`concern` LEFT JOIN `class_dramatica_issue` as class_dramatica_issue1 ON `class_dramatica_issue1`.`id`=`class_dramatica_themes`.`issue` ',
				'filterers' => array('issue' => 'issue'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			)
		),
		'storylines' => array(   
			'story' => array(
				'parent_table' => 'story',
				'parent_pk_field' => 'id',
				'parent_caption' => 'IF(CHAR_LENGTH(`story`.`id`) || CHAR_LENGTH(`story`.`story`), CONCAT_WS(\'\', `story`.`id`, \'  \', `story`.`story`), \'\')',
				'parent_from' => '`story` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'storyweaving_scene_no' => array(
				'parent_table' => 'storyweaving_scenes',
				'parent_pk_field' => 'id',
				'parent_caption' => '`storyweaving_scenes`.`id`',
				'parent_from' => '`storyweaving_scenes` LEFT JOIN `story` as story1 ON `story1`.`id`=`storyweaving_scenes`.`story` LEFT JOIN `class_dramatica_throughline` as class_dramatica_throughline1 ON `class_dramatica_throughline1`.`id`=`storyweaving_scenes`.`throughline` LEFT JOIN `class_dramatica_domain` as class_dramatica_domain1 ON `class_dramatica_domain1`.`id`=`storyweaving_scenes`.`domain` LEFT JOIN `class_dramatica_concern` as class_dramatica_concern1 ON `class_dramatica_concern1`.`id`=`storyweaving_scenes`.`concern` LEFT JOIN `class_dramatica_issue` as class_dramatica_issue1 ON `class_dramatica_issue1`.`id`=`storyweaving_scenes`.`issue` LEFT JOIN `class_dramatica_themes` as class_dramatica_themes1 ON `class_dramatica_themes1`.`id`=`storyweaving_scenes`.`theme` ',
				'filterers' => array('story' => 'story'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'storyweaving_scene' => array(
				'parent_table' => 'storyweaving_scenes',
				'parent_pk_field' => 'id',
				'parent_caption' => 'IF(CHAR_LENGTH(`storyweaving_scenes`.`step`) || CHAR_LENGTH(`storyweaving_scenes`.`throughline`), CONCAT_WS(\'\', `storyweaving_scenes`.`step`, \'  \', IF(    CHAR_LENGTH(`class_dramatica_throughline1`.`throughline`), CONCAT_WS(\'\',   `class_dramatica_throughline1`.`throughline`), \'\')), \'\')',
				'parent_from' => '`storyweaving_scenes` LEFT JOIN `story` as story1 ON `story1`.`id`=`storyweaving_scenes`.`story` LEFT JOIN `class_dramatica_throughline` as class_dramatica_throughline1 ON `class_dramatica_throughline1`.`id`=`storyweaving_scenes`.`throughline` LEFT JOIN `class_dramatica_domain` as class_dramatica_domain1 ON `class_dramatica_domain1`.`id`=`storyweaving_scenes`.`domain` LEFT JOIN `class_dramatica_concern` as class_dramatica_concern1 ON `class_dramatica_concern1`.`id`=`storyweaving_scenes`.`concern` LEFT JOIN `class_dramatica_issue` as class_dramatica_issue1 ON `class_dramatica_issue1`.`id`=`storyweaving_scenes`.`issue` LEFT JOIN `class_dramatica_themes` as class_dramatica_themes1 ON `class_dramatica_themes1`.`id`=`storyweaving_scenes`.`theme` ',
				'filterers' => array('story' => 'story'),
				'custom_query' => 'SELECT `storyweaving_scenes`.`id`, IF(CHAR_LENGTH(`storyweaving_scenes`.`step`) || CHAR_LENGTH(`storyweaving_scenes`.`throughline`), CONCAT_WS(\'\', `storyweaving_scenes`.`step`, \'  \', IF(    CHAR_LENGTH(`class_dramatica_throughline1`.`throughline`), CONCAT_WS(\'\',   `class_dramatica_throughline1`.`throughline`), \'\')), \'\') FROM `storyweaving_scenes` LEFT JOIN `story` as story1 ON `story1`.`id`=`storyweaving_scenes`.`story` LEFT JOIN `class_dramatica_throughline` as class_dramatica_throughline1 ON `class_dramatica_throughline1`.`id`=`storyweaving_scenes`.`throughline` LEFT JOIN `class_dramatica_domain` as class_dramatica_domain1 ON `class_dramatica_domain1`.`id`=`storyweaving_scenes`.`domain` LEFT JOIN `class_dramatica_concern` as class_dramatica_concern1 ON `class_dramatica_concern1`.`id`=`storyweaving_scenes`.`concern` LEFT JOIN `class_dramatica_issue` as class_dramatica_issue1 ON `class_dramatica_issue1`.`id`=`storyweaving_scenes`.`issue` LEFT JOIN `class_dramatica_themes` as class_dramatica_themes1 ON `class_dramatica_themes1`.`id`=`storyweaving_scenes`.`theme` ORDER BY 2',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'storyweaving_sequence' => array(
				'parent_table' => 'storyweaving_scenes',
				'parent_pk_field' => 'id',
				'parent_caption' => '`storyweaving_scenes`.`sequence`',
				'parent_from' => '`storyweaving_scenes` LEFT JOIN `story` as story1 ON `story1`.`id`=`storyweaving_scenes`.`story` LEFT JOIN `class_dramatica_throughline` as class_dramatica_throughline1 ON `class_dramatica_throughline1`.`id`=`storyweaving_scenes`.`throughline` LEFT JOIN `class_dramatica_domain` as class_dramatica_domain1 ON `class_dramatica_domain1`.`id`=`storyweaving_scenes`.`domain` LEFT JOIN `class_dramatica_concern` as class_dramatica_concern1 ON `class_dramatica_concern1`.`id`=`storyweaving_scenes`.`concern` LEFT JOIN `class_dramatica_issue` as class_dramatica_issue1 ON `class_dramatica_issue1`.`id`=`storyweaving_scenes`.`issue` LEFT JOIN `class_dramatica_themes` as class_dramatica_themes1 ON `class_dramatica_themes1`.`id`=`storyweaving_scenes`.`theme` ',
				'filterers' => array('story' => 'story'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'storyweaving_theme' => array(
				'parent_table' => 'storyweaving_scenes',
				'parent_pk_field' => 'id',
				'parent_caption' => 'IF(CHAR_LENGTH(`storyweaving_scenes`.`issue`) || CHAR_LENGTH(`storyweaving_scenes`.`theme`), CONCAT_WS(\'\', IF(    CHAR_LENGTH(`class_dramatica_issue1`.`issue`), CONCAT_WS(\'\',   `class_dramatica_issue1`.`issue`), \'\'), \' - \', IF(    CHAR_LENGTH(`class_dramatica_themes1`.`theme`), CONCAT_WS(\'\',   `class_dramatica_themes1`.`theme`), \'\')), \'\')',
				'parent_from' => '`storyweaving_scenes` LEFT JOIN `story` as story1 ON `story1`.`id`=`storyweaving_scenes`.`story` LEFT JOIN `class_dramatica_throughline` as class_dramatica_throughline1 ON `class_dramatica_throughline1`.`id`=`storyweaving_scenes`.`throughline` LEFT JOIN `class_dramatica_domain` as class_dramatica_domain1 ON `class_dramatica_domain1`.`id`=`storyweaving_scenes`.`domain` LEFT JOIN `class_dramatica_concern` as class_dramatica_concern1 ON `class_dramatica_concern1`.`id`=`storyweaving_scenes`.`concern` LEFT JOIN `class_dramatica_issue` as class_dramatica_issue1 ON `class_dramatica_issue1`.`id`=`storyweaving_scenes`.`issue` LEFT JOIN `class_dramatica_themes` as class_dramatica_themes1 ON `class_dramatica_themes1`.`id`=`storyweaving_scenes`.`theme` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'role' => array(
				'parent_table' => 'class_dramatica_archetype',
				'parent_pk_field' => 'id',
				'parent_caption' => 'IF(CHAR_LENGTH(`class_dramatica_archetype`.`archetype`), CONCAT_WS(\'\', `class_dramatica_archetype`.`archetype`, \' \'), \'\')',
				'parent_from' => '`class_dramatica_archetype` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'character' => array(
				'parent_table' => 'story_characters',
				'parent_pk_field' => 'id',
				'parent_caption' => 'IF(CHAR_LENGTH(`story_characters`.`character`) || CHAR_LENGTH(`story_characters`.`cw_name`), CONCAT_WS(\'\', `story_characters`.`character`, \' - \', `story_characters`.`cw_name`), \'\')',
				'parent_from' => '`story_characters` LEFT JOIN `story` as story1 ON `story1`.`id`=`story_characters`.`story` LEFT JOIN `class_dramatica_archetype` as class_dramatica_archetype1 ON `class_dramatica_archetype1`.`id`=`story_characters`.`role` LEFT JOIN `biblio_author` as biblio_author1 ON `biblio_author1`.`id`=`story_characters`.`agent_name` LEFT JOIN `class_nt` as class_nt1 ON `class_nt1`.`id`=`story_characters`.`noetictension` LEFT JOIN `class_im` as class_im1 ON `class_im1`.`id`=`story_characters`.`impression` ',
				'filterers' => array('story' => 'story', 'role' => 'role'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'characterevent_scene' => array(
				'parent_table' => 'code_encounters',
				'parent_pk_field' => 'id',
				'parent_caption' => 'IF(CHAR_LENGTH(`code_encounters`.`id`) || CHAR_LENGTH(`code_encounters`.`story_scene`), CONCAT_WS(\'\', `code_encounters`.`id`, \'  \', IF(    CHAR_LENGTH(`code_encounter_scenes3`.`scene`), CONCAT_WS(\'\',   `code_encounter_scenes3`.`scene`), \'\')), \'\')',
				'parent_from' => '`code_encounters` LEFT JOIN `biblio_author` as biblio_author1 ON `biblio_author1`.`id`=`code_encounters`.`agentA` LEFT JOIN `biblio_author` as biblio_author2 ON `biblio_author2`.`id`=`code_encounters`.`authorA` LEFT JOIN `biblio_doc` as biblio_doc1 ON `biblio_doc1`.`id`=`code_encounters`.`bibliographyA` LEFT JOIN `biblio_trascript` as biblio_trascript1 ON `biblio_trascript1`.`id`=`code_encounters`.`transcriptA` LEFT JOIN `biblio_token` as biblio_token1 ON `biblio_token1`.`id`=`code_encounters`.`tokenA` LEFT JOIN `code_encounter_scenes` as code_encounter_scenes1 ON `code_encounter_scenes1`.`id`=`code_encounters`.`sceneA` LEFT JOIN `biblio_author` as biblio_author3 ON `biblio_author3`.`id`=`code_encounters`.`agentB` LEFT JOIN `biblio_author` as biblio_author4 ON `biblio_author4`.`id`=`code_encounters`.`authorB` LEFT JOIN `biblio_doc` as biblio_doc2 ON `biblio_doc2`.`id`=`code_encounters`.`bibliographyB` LEFT JOIN `biblio_trascript` as biblio_trascript2 ON `biblio_trascript2`.`id`=`code_encounters`.`transcriptB` LEFT JOIN `biblio_token` as biblio_token2 ON `biblio_token2`.`id`=`code_encounters`.`tokenB` LEFT JOIN `code_encounter_scenes` as code_encounter_scenes2 ON `code_encounter_scenes2`.`id`=`code_encounters`.`sceneB` LEFT JOIN `code_encounter_scenes` as code_encounter_scenes3 ON `code_encounter_scenes3`.`id`=`code_encounters`.`story_scene` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'character_event' => array(
				'parent_table' => 'code_encounters',
				'parent_pk_field' => 'id',
				'parent_caption' => 'IF(CHAR_LENGTH(`code_encounters`.`sceneA`) || CHAR_LENGTH(`code_encounters`.`sceneB`), CONCAT_WS(\'\', IF(    CHAR_LENGTH(`code_encounter_scenes1`.`scene`), CONCAT_WS(\'\',   `code_encounter_scenes1`.`scene`), \'\'), \'|-| \', IF(    CHAR_LENGTH(`code_encounter_scenes2`.`scene`), CONCAT_WS(\'\',   `code_encounter_scenes2`.`scene`, \'  \'), \'\')), \'\')',
				'parent_from' => '`code_encounters` LEFT JOIN `biblio_author` as biblio_author1 ON `biblio_author1`.`id`=`code_encounters`.`agentA` LEFT JOIN `biblio_author` as biblio_author2 ON `biblio_author2`.`id`=`code_encounters`.`authorA` LEFT JOIN `biblio_doc` as biblio_doc1 ON `biblio_doc1`.`id`=`code_encounters`.`bibliographyA` LEFT JOIN `biblio_trascript` as biblio_trascript1 ON `biblio_trascript1`.`id`=`code_encounters`.`transcriptA` LEFT JOIN `biblio_token` as biblio_token1 ON `biblio_token1`.`id`=`code_encounters`.`tokenA` LEFT JOIN `code_encounter_scenes` as code_encounter_scenes1 ON `code_encounter_scenes1`.`id`=`code_encounters`.`sceneA` LEFT JOIN `biblio_author` as biblio_author3 ON `biblio_author3`.`id`=`code_encounters`.`agentB` LEFT JOIN `biblio_author` as biblio_author4 ON `biblio_author4`.`id`=`code_encounters`.`authorB` LEFT JOIN `biblio_doc` as biblio_doc2 ON `biblio_doc2`.`id`=`code_encounters`.`bibliographyB` LEFT JOIN `biblio_trascript` as biblio_trascript2 ON `biblio_trascript2`.`id`=`code_encounters`.`transcriptB` LEFT JOIN `biblio_token` as biblio_token2 ON `biblio_token2`.`id`=`code_encounters`.`tokenB` LEFT JOIN `code_encounter_scenes` as code_encounter_scenes2 ON `code_encounter_scenes2`.`id`=`code_encounters`.`sceneB` LEFT JOIN `code_encounter_scenes` as code_encounter_scenes3 ON `code_encounter_scenes3`.`id`=`code_encounters`.`story_scene` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			)
		),
		'dictionary' => array(  
		),
		'class_agent_type1' => array(  
		),
		'class_agent_type2' => array(  
		),
		'class_authority_agent' => array(  
		),
		'class_authority_library' => array(  
		),
		'class_bibliography_genre' => array(  
		),
		'class_bibliography_type' => array(  
		),
		'class_dramatica_archetype' => array(  
		),
		'class_dramatica_domain' => array(  
		),
		'class_dramatica_concern' => array(   
			'domain' => array(
				'parent_table' => 'class_dramatica_domain',
				'parent_pk_field' => 'id',
				'parent_caption' => '`class_dramatica_domain`.`domain`',
				'parent_from' => '`class_dramatica_domain` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			)
		),
		'class_dramatica_issue' => array(   
			'domain' => array(
				'parent_table' => 'class_dramatica_domain',
				'parent_pk_field' => 'id',
				'parent_caption' => '`class_dramatica_domain`.`domain`',
				'parent_from' => '`class_dramatica_domain` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'concern' => array(
				'parent_table' => 'class_dramatica_concern',
				'parent_pk_field' => 'id',
				'parent_caption' => '`class_dramatica_concern`.`concern`',
				'parent_from' => '`class_dramatica_concern` LEFT JOIN `class_dramatica_domain` as class_dramatica_domain1 ON `class_dramatica_domain1`.`id`=`class_dramatica_concern`.`domain` ',
				'filterers' => array('domain' => 'domain'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			)
		),
		'class_dramatica_themes' => array(   
			'domain' => array(
				'parent_table' => 'class_dramatica_domain',
				'parent_pk_field' => 'id',
				'parent_caption' => '`class_dramatica_domain`.`domain`',
				'parent_from' => '`class_dramatica_domain` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'concern' => array(
				'parent_table' => 'class_dramatica_concern',
				'parent_pk_field' => 'id',
				'parent_caption' => '`class_dramatica_concern`.`concern`',
				'parent_from' => '`class_dramatica_concern` LEFT JOIN `class_dramatica_domain` as class_dramatica_domain1 ON `class_dramatica_domain1`.`id`=`class_dramatica_concern`.`domain` ',
				'filterers' => array('domain' => 'domain'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'issue' => array(
				'parent_table' => 'class_dramatica_issue',
				'parent_pk_field' => 'id',
				'parent_caption' => '`class_dramatica_issue`.`issue`',
				'parent_from' => '`class_dramatica_issue` LEFT JOIN `class_dramatica_domain` as class_dramatica_domain1 ON `class_dramatica_domain1`.`id`=`class_dramatica_issue`.`domain` LEFT JOIN `class_dramatica_concern` as class_dramatica_concern1 ON `class_dramatica_concern1`.`id`=`class_dramatica_issue`.`concern` ',
				'filterers' => array('domain' => 'domain', 'concern' => 'concern'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			)
		),
		'class_dramatica_throughline' => array(  
		),
		'class_im' => array(  
		),
		'class_language' => array(  
		),
		'class_nt' => array(  
		),
		'class_character_element' => array(  
		),
		'class_rights' => array(  
		)
	);


	// receive and verify user input
	$table_name = $_REQUEST['t'];
	$field_name = $_REQUEST['f'];
	$search_id = makeSafe(iconv('UTF-8', datalist_db_encoding, $_REQUEST['id']));
	$selected_text = iconv('UTF-8', datalist_db_encoding, $_REQUEST['text']);
	$returnOptions = ($_REQUEST['o'] == 1 ? true : false);
	$page = intval($_REQUEST['p']);
	if($page < 1)  $page = 1;
	$skip = $results_per_page * ($page - 1);
	$search_term = makeSafe(iconv('UTF-8', datalist_db_encoding, $_REQUEST['s']));

	if(!isset($lookups[$table_name][$field_name])) die('{ "error": "Invalid table or field." }');

	// can user access the requested table?
	$perm = getTablePermissions($table_name);
	if(!$perm[0] && !$search_id) die('{ "error": "' . addslashes($Translation['tableAccessDenied']) . '" }');

	$field = $lookups[$table_name][$field_name];

	$wheres = array();

	// search term provided?
	if($search_term){
		$wheres[] = "{$field['parent_caption']} like '%{$search_term}%'";
	}

	// any filterers specified?
	if(is_array($field['filterers'])){
		foreach($field['filterers'] as $filterer => $filterer_parent){
			$get = (isset($_REQUEST["filterer_{$filterer}"]) ? $_REQUEST["filterer_{$filterer}"] : false);
			if($get){
				$wheres[] = "`{$field['parent_table']}`.`$filterer_parent`='" . makeSafe($get) . "'";
			}
		}
	}

	// inherit permissions?
	if($field['inherit_permissions']){
		$inherit = permissions_sql($field['parent_table']);
		if($inherit === false && !$search_id) die($Translation['tableAccessDenied']);

		if($inherit['where']) $wheres[] = $inherit['where'];
		if($inherit['from']) $field['parent_from'] .= ", {$inherit['from']}";
	}

	// single value?
	if($field['list_type'] != 2 && $search_id){
		$wheres[] = "`{$field['parent_table']}`.`{$field['parent_pk_field']}`='{$search_id}'";
	}

	if(count($wheres)){
		$where = 'WHERE ' . implode(' AND ', $wheres);
	}

	// define the combo and return the code
	$combo = new DataCombo;
	if($field['custom_query']){
		$qm = array(); $custom_where = ''; $custom_order_by = '2';
		$combo->Query = $field['custom_query'];

		if(preg_match('/ order by (.*)$/i', $combo->Query, $qm)){
			$custom_order_by = $qm[1];
			$combo->Query = preg_replace('/ order by .*$/i', '', $combo->Query);
		}

		if(preg_match('/ where (.*)$/i', $combo->Query, $qm)){
			$custom_where = $qm[1];
			$combo->Query = preg_replace('/ where .*$/i', '', $combo->Query);
		}

		if($where && $custom_where){
			$combo->Query .=  " {$where} AND ({$custom_where}) ORDER BY {$custom_order_by}";
		}elseif($custom_where){
			$combo->Query .=  " WHERE {$custom_where} ORDER BY {$custom_order_by}";
		}else{
			$combo->Query .=  " {$where} ORDER BY {$custom_order_by}";
		}

		$query_match = array();
		preg_match('/select (.*) from (.*)$/i', $combo->Query, $query_match);

		if(isset($query_match[2])){
			$count_query = "SELECT count(1) FROM {$query_match[2]}";
		}else{
			$count_query = '';
		}
	}else{
		$combo->Query = "SELECT " . ($field['inherit_permissions'] ? 'DISTINCT ' : '') . "`{$field['parent_table']}`.`{$field['parent_pk_field']}`, {$field['parent_caption']} FROM {$field['parent_from']} {$where} ORDER BY 2";
		$count_query = "SELECT count(1) FROM {$field['parent_from']} {$where}";
	}
	$combo->table = $table_name;
	$combo->parent_table = $field['parent_table'];
	$combo->SelectName = $field_name;
	$combo->ListType = $field['list_type'];
	if($search_id){
		$combo->SelectedData = $search_id;
	}elseif($selected_text){
		$combo->SelectedData = getValueGivenCaption($combo->Query, $selected_text);
	}

	if($field['list_type'] == 2){
		$combo->Render();
		$combo->HTML = str_replace('<select ', '<select onchange="' . $field_name . '_changed();" ', $combo->HTML);

		// return response
		if($returnOptions){
			?><span id="<?php echo $field_name; ?>-combo-list"><?php echo $combo->HTML; ?></span><?php
		}else{
			?>
				<span id="<?php echo $field_name; ?>-match-text"><?php echo $combo->MatchText; ?></span>
				<input type="hidden" id="<?php echo $field_name; ?>" value="<?php echo htmlspecialchars($combo->SelectedData); ?>" />
			<?php
		}
	}else{
		/* return json */
		header('Content-type: application/json');

		if(!preg_match('/ limit .+/i', $combo->Query)){
			if(!$search_id) $combo->Query .= " LIMIT {$skip}, {$results_per_page}";
			if($search_id) $combo->Query .= " LIMIT 1";
		}

		$prepared_data = array();

		// specific caption provided and list_type is not radio?
		if(!$search_id && $selected_text){
			$search_id = getValueGivenCaption($combo->Query, $selected_text);
			if($search_id) $prepared_data[] = array('id' => $search_id, 'text' => $selected_text);
		}else{
			$res = sql($combo->Query, $eo);
			while($row = db_fetch_row($res)){
				if(empty($prepared_data) && $page == 1 && !$search_id){
					if($field['not_null']){
						$prepared_data[] = array('id' => '', 'text' => "<{$Translation['none']}>");
					}else{
						$prepared_data[] = array('id' => empty_lookup_value, 'text' => "<{$Translation['none']}>");
					}
				}
				$prepared_data[] = array('id' => iconv(datalist_db_encoding, 'UTF-8', $row[0]), 'text' => iconv(datalist_db_encoding, 'UTF-8', $row[1]));
			}
		}

		if(empty($prepared_data)){ $prepared_data[] = array('id' => '', 'text' => "<{$Translation['none']}>"); }

		echo json_encode(array(
			'results' => $prepared_data,
			'more' => (@db_num_rows($res) >= $results_per_page),
			'elapsed' => round(microtime(true) - $start_ts, 3)
		));
	}

