<?php

// Data functions for table biblio_trascript

// This script and data application were generated by AppGini 5.31
// Download AppGini for free from http://bigprof.com/appgini/download/

function biblio_trascript_insert(){
	global $Translation;

	if($_GET['insert_x']!=''){$_POST=$_GET;}

	// mm: can member insert record?
	$arrPerm=getTablePermissions('biblio_trascript');
	if(!$arrPerm[1]){
		return false;
	}

	$data['author'] = makeSafe($_POST['author']);
		if($data['author'] == empty_lookup_value){ $data['author'] = ''; }
	$data['bibliography_title'] = makeSafe($_POST['bibliography_title']);
		if($data['bibliography_title'] == empty_lookup_value){ $data['bibliography_title'] = ''; }
	$data['trascriber_memberID'] = makeSafe($_POST['trascriber_memberID']);
		if($data['trascriber_memberID'] == empty_lookup_value){ $data['trascriber_memberID'] = ''; }
	$data['transcript_title'] = makeSafe($_POST['transcript_title']);
		if($data['transcript_title'] == empty_lookup_value){ $data['transcript_title'] = ''; }
	$data['transcript'] = PrepareUploadedFile('transcript', 92160000,'txt|doc|docx|docm|odt|pdf|rtf', false, '');
	$data['credits'] = PrepareUploadedFile('credits', 102400,'txt|doc|docx|docm|odt|pdf|rtf', false, '');

	/* for empty upload fields, when saving a copy of an existing record, copy the original upload field */
	if($_REQUEST['SelectedID']){
		$res = sql("select * from biblio_trascript where id='" . makeSafe($_REQUEST['SelectedID']) . "'");
		if($row = db_fetch_assoc($res)){
			if(!$data['transcript']) $data['transcript'] = makeSafe($row['transcript']);
			if(!$data['credits']) $data['credits'] = makeSafe($row['credits']);
		}
	}

	// hook: biblio_trascript_before_insert
	if(function_exists('biblio_trascript_before_insert')){
		$args=array();
		if(!biblio_trascript_before_insert($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('insert into `biblio_trascript` set       `author`=' . (($data['author'] !== '' && $data['author'] !== NULL) ? "'{$data['author']}'" : 'NULL') . ', `bibliography_title`=' . (($data['bibliography_title'] !== '' && $data['bibliography_title'] !== NULL) ? "'{$data['bibliography_title']}'" : 'NULL') . ', `trascriber_memberID`=' . (($data['trascriber_memberID'] !== '' && $data['trascriber_memberID'] !== NULL) ? "'{$data['trascriber_memberID']}'" : 'NULL') . ', `transcript_title`=' . (($data['transcript_title'] !== '' && $data['transcript_title'] !== NULL) ? "'{$data['transcript_title']}'" : 'NULL') . ', ' . ($data['transcript']!='' ? "`transcript`='{$data['transcript']}'" : ($_POST['transcript_remove'] != 1 ? '`transcript`=`transcript`' : '`transcript`=NULL')) . ', ' . ($data['credits']!='' ? "`credits`='{$data['credits']}'" : ($_POST['credits_remove'] != 1 ? '`credits`=`credits`' : '`credits`=NULL')), $o);
	if($o['error']!=''){
		echo $o['error'];
		echo "<a href=\"biblio_trascript_view.php?addNew_x=1\">{$Translation['< back']}</a>";
		exit;
	}

	$recID=db_insert_id(db_link());

	// hook: biblio_trascript_after_insert
	if(function_exists('biblio_trascript_after_insert')){
		$res = sql("select * from `biblio_trascript` where `id`='" . makeSafe($recID) . "' limit 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID);
		$args=array();
		if(!biblio_trascript_after_insert($data, getMemberInfo(), $args)){ return (get_magic_quotes_gpc() ? stripslashes($recID) : $recID); }
	}

	// mm: save ownership data
	sql("insert into membership_userrecords set tableName='biblio_trascript', pkValue='$recID', memberID='".getLoggedMemberID()."', dateAdded='".time()."', dateUpdated='".time()."', groupID='".getLoggedGroupID()."'", $eo);

	return (get_magic_quotes_gpc() ? stripslashes($recID) : $recID);
}

function biblio_trascript_delete($selected_id, $AllowDeleteOfParents=false, $skipChecks=false){
	// insure referential integrity ...
	global $Translation;
	$selected_id=makeSafe($selected_id);

	// mm: can member delete record?
	$arrPerm=getTablePermissions('biblio_trascript');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='biblio_trascript' and pkValue='$selected_id'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='biblio_trascript' and pkValue='$selected_id'");
	if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
		// delete allowed, so continue ...
	}else{
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: biblio_trascript_before_delete
	if(function_exists('biblio_trascript_before_delete')){
		$args=array();
		if(!biblio_trascript_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'];
	}

	// child table: biblio_token
	$res = sql("select `id` from `biblio_trascript` where `id`='$selected_id'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("select count(1) from `biblio_token` where `transcript`='".addslashes($id[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "biblio_token", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "biblio_token", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='biblio_trascript_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='biblio_trascript_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	// child table: code_invivo
	$res = sql("select `id` from `biblio_trascript` where `id`='$selected_id'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("select count(1) from `code_invivo` where `transcript`='".addslashes($id[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "code_invivo", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "code_invivo", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='biblio_trascript_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='biblio_trascript_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	// child table: code_herme
	$res = sql("select `id` from `biblio_trascript` where `id`='$selected_id'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("select count(1) from `code_herme` where `transcript`='".addslashes($id[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "code_herme", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "code_herme", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='biblio_trascript_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='biblio_trascript_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	// child table: code_chrev_scenes
	$res = sql("select `id` from `biblio_trascript` where `id`='$selected_id'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("select count(1) from `code_chrev_scenes` where `transcript`='".addslashes($id[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "code_chrev_scenes", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "code_chrev_scenes", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='biblio_trascript_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='biblio_trascript_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	// child table: code_character_development
	$res = sql("select `id` from `biblio_trascript` where `id`='$selected_id'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("select count(1) from `code_character_development` where `transcript`='".addslashes($id[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "code_character_development", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "code_character_development", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='biblio_trascript_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='biblio_trascript_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	// child table: code_encounters
	$res = sql("select `id` from `biblio_trascript` where `id`='$selected_id'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("select count(1) from `code_encounters` where `transcriptA`='".addslashes($id[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "code_encounters", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "code_encounters", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='biblio_trascript_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='biblio_trascript_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	// child table: code_encounters
	$res = sql("select `id` from `biblio_trascript` where `id`='$selected_id'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("select count(1) from `code_encounters` where `transcriptB`='".addslashes($id[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "code_encounters", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "code_encounters", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='biblio_trascript_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='biblio_trascript_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	// delete file stored in the 'transcript' field
	$res = sql("select `transcript` from `biblio_trascript` where `id`='$selected_id'", $eo);
	if($row=@db_fetch_row($res)){
		if($row[0]!=''){
			@unlink(getUploadDir('').$row[0]);
		}
	}

	sql("delete from `biblio_trascript` where `id`='$selected_id'", $eo);

	// hook: biblio_trascript_after_delete
	if(function_exists('biblio_trascript_after_delete')){
		$args=array();
		biblio_trascript_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("delete from membership_userrecords where tableName='biblio_trascript' and pkValue='$selected_id'", $eo);
}

function biblio_trascript_update($selected_id){
	global $Translation;

	if($_GET['update_x']!=''){$_POST=$_GET;}

	// mm: can member edit record?
	$arrPerm=getTablePermissions('biblio_trascript');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='biblio_trascript' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='biblio_trascript' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){ // allow update?
		// update allowed, so continue ...
	}else{
		return false;
	}

	$data['author'] = makeSafe($_POST['author']);
		if($data['author'] == empty_lookup_value){ $data['author'] = ''; }
	$data['bibliography_title'] = makeSafe($_POST['bibliography_title']);
		if($data['bibliography_title'] == empty_lookup_value){ $data['bibliography_title'] = ''; }
	$data['trascriber_memberID'] = makeSafe($_POST['trascriber_memberID']);
		if($data['trascriber_memberID'] == empty_lookup_value){ $data['trascriber_memberID'] = ''; }
	$data['transcript_title'] = makeSafe($_POST['transcript_title']);
		if($data['transcript_title'] == empty_lookup_value){ $data['transcript_title'] = ''; }
	$data['selectedID']=makeSafe($selected_id);
	if($_POST['transcript_remove'] == 1){
		$data['transcript'] = '';
		// delete file from server
		$res = sql("select `transcript` from `biblio_trascript` where `id`='".makeSafe($selected_id)."'", $eo);
		if($row=@db_fetch_row($res)){
			if($row[0]!=''){
				@unlink(getUploadDir('').$row[0]);
			}
		}
	}else{
		$data['transcript'] = PrepareUploadedFile('transcript', 92160000, 'txt|doc|docx|docm|odt|pdf|rtf', false, "");
		// delete file from server
		if($data['transcript'] != ''){
			$res = sql("select `transcript` from `biblio_trascript` where `id`='".makeSafe($selected_id)."'", $eo);
			if($row=@db_fetch_row($res)){
				if($row[0]!=''){
					@unlink(getUploadDir('').$row[0]);
				}
			}
		}
	}
	if($_POST['credits_remove'] == 1){
		$data['credits'] = '';
	}else{
		$data['credits'] = PrepareUploadedFile('credits', 102400, 'txt|doc|docx|docm|odt|pdf|rtf', false, "");
	}

	// hook: biblio_trascript_before_update
	if(function_exists('biblio_trascript_before_update')){
		$args=array();
		if(!biblio_trascript_before_update($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('update `biblio_trascript` set       `author`=' . (($data['author'] !== '' && $data['author'] !== NULL) ? "'{$data['author']}'" : 'NULL') . ', `bibliography_title`=' . (($data['bibliography_title'] !== '' && $data['bibliography_title'] !== NULL) ? "'{$data['bibliography_title']}'" : 'NULL') . ', `trascriber_memberID`=' . (($data['trascriber_memberID'] !== '' && $data['trascriber_memberID'] !== NULL) ? "'{$data['trascriber_memberID']}'" : 'NULL') . ', `transcript_title`=' . (($data['transcript_title'] !== '' && $data['transcript_title'] !== NULL) ? "'{$data['transcript_title']}'" : 'NULL') . ', ' . ($data['transcript']!='' ? "`transcript`='{$data['transcript']}'" : ($_POST['transcript_remove'] != 1 ? '`transcript`=`transcript`' : '`transcript`=NULL')) . ', ' . ($data['credits']!='' ? "`credits`='{$data['credits']}'" : ($_POST['credits_remove'] != 1 ? '`credits`=`credits`' : '`credits`=NULL')) . " where `id`='".makeSafe($selected_id)."'", $o);
	if($o['error']!=''){
		echo $o['error'];
		echo '<a href="biblio_trascript_view.php?SelectedID='.urlencode($selected_id)."\">{$Translation['< back']}</a>";
		exit;
	}


	// hook: biblio_trascript_after_update
	if(function_exists('biblio_trascript_after_update')){
		$res = sql("SELECT * FROM `biblio_trascript` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = $data['id'];
		$args = array();
		if(!biblio_trascript_after_update($data, getMemberInfo(), $args)){ return; }
	}

	// mm: update ownership data
	sql("update membership_userrecords set dateUpdated='".time()."' where tableName='biblio_trascript' and pkValue='".makeSafe($selected_id)."'", $eo);

}

function biblio_trascript_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0){
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm=getTablePermissions('biblio_trascript');
	if(!$arrPerm[1] && $selected_id==''){ return ''; }
	$AllowInsert = ($arrPerm[1] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != ''){
		$dvprint = true;
	}

	$filterer_author = thisOr(undo_magic_quotes($_REQUEST['filterer_author']), '');
	$filterer_bibliography_title = thisOr(undo_magic_quotes($_REQUEST['filterer_bibliography_title']), '');

	// populate filterers, starting from children to grand-parents
	if($filterer_bibliography_title && !$filterer_author) $filterer_author = sqlValue("select author_name from biblio_doc where id='" . makeSafe($filterer_bibliography_title) . "'");

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: author
	$combo_author = new DataCombo;
	// combobox: bibliography_title, filterable by: author
	$combo_bibliography_title = new DataCombo;

	if($selected_id){
		// mm: check member permissions
		if(!$arrPerm[2]){
			return "";
		}
		// mm: who is the owner?
		$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='biblio_trascript' and pkValue='".makeSafe($selected_id)."'");
		$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='biblio_trascript' and pkValue='".makeSafe($selected_id)."'");
		if($arrPerm[2]==1 && getLoggedMemberID()!=$ownerMemberID){
			return "";
		}
		if($arrPerm[2]==2 && getLoggedGroupID()!=$ownerGroupID){
			return "";
		}

		// can edit?
		if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){
			$AllowUpdate=1;
		}else{
			$AllowUpdate=0;
		}

		$res = sql("select * from `biblio_trascript` where `id`='".makeSafe($selected_id)."'", $eo);
		if(!($row = db_fetch_array($res))){
			return error_message($Translation['No records found']);
		}
		$urow = $row; /* unsanitized data */
		$hc = new CI_Input();
		$row = $hc->xss_clean($row); /* sanitize data */
		$combo_author->SelectedData = $row['author'];
		$combo_bibliography_title->SelectedData = $row['bibliography_title'];
	}else{
		$combo_author->SelectedData = $filterer_author;
		$combo_bibliography_title->SelectedData = $filterer_bibliography_title;
	}
	$combo_author->HTML = '<span id="author-container' . $rnd1 . '"></span><input type="hidden" name="author" id="author' . $rnd1 . '">';
	$combo_author->MatchText = '<span id="author-container-readonly' . $rnd1 . '"></span><input type="hidden" name="author" id="author' . $rnd1 . '">';
	$combo_bibliography_title->HTML = '<span id="bibliography_title-container' . $rnd1 . '"></span><input type="hidden" name="bibliography_title" id="bibliography_title' . $rnd1 . '">';
	$combo_bibliography_title->MatchText = '<span id="bibliography_title-container-readonly' . $rnd1 . '"></span><input type="hidden" name="bibliography_title" id="bibliography_title' . $rnd1 . '">';

	ob_start();
	?>

	<script>
		// initial lookup values
		var current_author__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['author'] : $filterer_author); ?>"};
		var current_bibliography_title__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['bibliography_title'] : $filterer_bibliography_title); ?>"};

		jQuery(function() {
			if(typeof(author_reload__RAND__) == 'function') author_reload__RAND__();
			<?php echo (!$AllowUpdate || $dvprint ? 'if(typeof(bibliography_title_reload__RAND__) == \'function\') bibliography_title_reload__RAND__(current_author__RAND__.value);' : ''); ?>
		});
		function author_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			jQuery("#author-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					jQuery.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: current_author__RAND__.value, t: 'biblio_trascript', f: 'author' }
					}).done(function(resp){
						c({
							id: resp.results[0].id,
							text: resp.results[0].text
						});
						jQuery('[name="author"]').val(resp.results[0].id);
						jQuery('[id=author-container-readonly__RAND__]').html('<span id="author-match-text">' + resp.results[0].text + '</span>');

						if(typeof(bibliography_title_reload__RAND__) == 'function') bibliography_title_reload__RAND__(current_author__RAND__.value);

						if(typeof(author_update_autofills__RAND__) == 'function') author_update_autofills__RAND__();
					});
				},
				width: '100%',
				formatNoMatches: function(term){ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 10,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ return { s: term, p: page, t: 'biblio_trascript', f: 'author' }; },
					results: function(resp, page){ return resp; }
				}
			}).on('change', function(e){
				current_author__RAND__.value = e.added.id;
				current_author__RAND__.text = e.added.text;
				jQuery('[name="author"]').val(e.added.id);

						if(typeof(bibliography_title_reload__RAND__) == 'function') bibliography_title_reload__RAND__(current_author__RAND__.value);

				if(typeof(author_update_autofills__RAND__) == 'function') author_update_autofills__RAND__();
			});
		<?php }else{ ?>

			jQuery.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: current_author__RAND__.value, t: 'biblio_trascript', f: 'author' }
			}).done(function(resp){
				jQuery('[id=author-container__RAND__], [id=author-container-readonly__RAND__]').html('<span id="author-match-text">' + resp.results[0].text + '</span>');

				if(typeof(author_update_autofills__RAND__) == 'function') author_update_autofills__RAND__();
			});
		<?php } ?>

		}
		function bibliography_title_reload__RAND__(filterer_author){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			jQuery("#bibliography_title-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					jQuery.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { filterer_author: filterer_author, id: current_bibliography_title__RAND__.value, t: 'biblio_trascript', f: 'bibliography_title' }
					}).done(function(resp){
						c({
							id: resp.results[0].id,
							text: resp.results[0].text
						});
						jQuery('[name="bibliography_title"]').val(resp.results[0].id);
						jQuery('[id=bibliography_title-container-readonly__RAND__]').html('<span id="bibliography_title-match-text">' + resp.results[0].text + '</span>');


						if(typeof(bibliography_title_update_autofills__RAND__) == 'function') bibliography_title_update_autofills__RAND__();
					});
				},
				width: '100%',
				formatNoMatches: function(term){ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 10,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ return { filterer_author: filterer_author, s: term, p: page, t: 'biblio_trascript', f: 'bibliography_title' }; },
					results: function(resp, page){ return resp; }
				}
			}).on('change', function(e){
				current_bibliography_title__RAND__.value = e.added.id;
				current_bibliography_title__RAND__.text = e.added.text;
				jQuery('[name="bibliography_title"]').val(e.added.id);


				if(typeof(bibliography_title_update_autofills__RAND__) == 'function') bibliography_title_update_autofills__RAND__();
			});
		<?php }else{ ?>

			jQuery.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: current_bibliography_title__RAND__.value, t: 'biblio_trascript', f: 'bibliography_title' }
			}).done(function(resp){
				jQuery('[id=bibliography_title-container__RAND__], [id=bibliography_title-container-readonly__RAND__]').html('<span id="bibliography_title-match-text">' + resp.results[0].text + '</span>');

				if(typeof(bibliography_title_update_autofills__RAND__) == 'function') bibliography_title_update_autofills__RAND__();
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_contents());
	ob_end_clean();


	// code for template based detail view forms

	// open the detail view template
	if($dvprint){
		$templateCode = @file_get_contents('./templates/biblio_trascript_templateDVP.html');
	}else{
		$templateCode = @file_get_contents('./templates/biblio_trascript_templateDV.html');
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Trascript details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', ($_REQUEST['Embedded'] ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert){
		if(!$selected_id) $templateCode=str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return biblio_trascript_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return biblio_trascript_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	}else{
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']){
		$backAction = 'window.parent.jQuery(\'.modal\').modal(\'hide\'); return false;';
	}else{
		$backAction = '$$(\'form\')[0].writeAttribute(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id){
		if(!$_REQUEST['Embedded']) $templateCode=str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$$(\'form\')[0].writeAttribute(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate){
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return biblio_trascript_validateData();"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		}else{
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		}else{
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	}else{
		$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)){
		$jsReadOnly .= "\tjQuery('#author').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#author_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#bibliography_title').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#bibliography_title_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#trascriber_memberID').replaceWith('<p class=\"form-control-static\" id=\"trascriber_memberID\">' + (jQuery('#trascriber_memberID').val() || '') + '</p>');\n";
		$jsReadOnly .= "\tjQuery('#transcript_title').replaceWith('<p class=\"form-control-static\" id=\"transcript_title\">' + (jQuery('#transcript_title').val() || '') + '</p>');\n";
		$jsReadOnly .= "\tjQuery('#transcript').replaceWith('<p class=\"form-control-static\" id=\"transcript\">' + (jQuery('#transcript').val() || '') + '</p>');\n";
		$jsReadOnly .= "\tjQuery('#transcript, #transcript-edit-link').hide();\n";
		$jsReadOnly .= "\tjQuery('#credits').replaceWith('<p class=\"form-control-static\" id=\"credits\">' + (jQuery('#credits').val() || '') + '</p>');\n";
		$jsReadOnly .= "\tjQuery('#credits, #credits-edit-link').hide();\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	}elseif($AllowInsert){
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
			$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode=str_replace('<%%COMBO(author)%%>', $combo_author->HTML, $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(author)%%>', $combo_author->MatchText, $templateCode);
	$templateCode=str_replace('<%%URLCOMBOTEXT(author)%%>', urlencode($combo_author->MatchText), $templateCode);
	$templateCode=str_replace('<%%COMBO(bibliography_title)%%>', $combo_bibliography_title->HTML, $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(bibliography_title)%%>', $combo_bibliography_title->MatchText, $templateCode);
	$templateCode=str_replace('<%%URLCOMBOTEXT(bibliography_title)%%>', urlencode($combo_bibliography_title->MatchText), $templateCode);

	// process foreign key links
	if($selected_id){
		$templateCode=str_replace('<%%PLINK(author)%%>', ($combo_author->SelectedData ? "<span id=\"biblio_author_plink1\" class=\"hidden\"><a class=\"btn btn-default\" href=\"biblio_author_view.php?SelectedID=" . urlencode($combo_author->SelectedData) . "\"><i class=\"glyphicon glyphicon-search\"></i></a></span>" : ''), $templateCode);
		$templateCode=str_replace('<%%PLINK(bibliography_title)%%>', ($combo_bibliography_title->SelectedData ? "<span id=\"biblio_doc_plink2\" class=\"hidden\"><a class=\"btn btn-default\" href=\"biblio_doc_view.php?SelectedID=" . urlencode($combo_bibliography_title->SelectedData) . "\"><i class=\"glyphicon glyphicon-search\"></i></a></span>" : ''), $templateCode);
	}

	// process images
	$templateCode=str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(author)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(bibliography_title)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(trascriber_memberID)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(transcript_title)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(transcript)%%>', ($noUploads ? '' : '<br><input type=hidden name=MAX_FILE_SIZE value=92160000>'.$Translation['upload image'].' <input type="file" name="transcript">'), $templateCode);
	if($AllowUpdate && $row['transcript']!=''){
		$templateCode=str_replace('<%%REMOVEFILE(transcript)%%>', '<br><input type="checkbox" name="transcript_remove" id="transcript_remove" value="1"> <label for="transcript_remove" style="color: red; font-weight: bold;">'.$Translation['remove image'].'</label>', $templateCode);
	}else{
		$templateCode=str_replace('<%%REMOVEFILE(transcript)%%>', '', $templateCode);
	}
	$templateCode=str_replace('<%%UPLOADFILE(credits)%%>', ($noUploads ? '' : '<br><input type=hidden name=MAX_FILE_SIZE value=102400>'.$Translation['upload image'].' <input type="file" name="credits">'), $templateCode);
	if($AllowUpdate && $row['credits']!=''){
		$templateCode=str_replace('<%%REMOVEFILE(credits)%%>', '<br><input type="checkbox" name="credits_remove" id="credits_remove" value="1"> <label for="credits_remove" style="color: red; font-weight: bold;">'.$Translation['remove image'].'</label>', $templateCode);
	}else{
		$templateCode=str_replace('<%%REMOVEFILE(credits)%%>', '', $templateCode);
	}

	// process values
	if($selected_id){
		$templateCode=str_replace('<%%VALUE(id)%%>', htmlspecialchars($row['id'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		$templateCode=str_replace('<%%VALUE(author)%%>', htmlspecialchars($row['author'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(author)%%>', urlencode($urow['author']), $templateCode);
		$templateCode=str_replace('<%%VALUE(bibliography_title)%%>', htmlspecialchars($row['bibliography_title'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(bibliography_title)%%>', urlencode($urow['bibliography_title']), $templateCode);
		$templateCode=str_replace('<%%VALUE(trascriber_memberID)%%>', htmlspecialchars($row['trascriber_memberID'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(trascriber_memberID)%%>', urlencode($urow['trascriber_memberID']), $templateCode);
		$templateCode=str_replace('<%%VALUE(transcript_title)%%>', htmlspecialchars($row['transcript_title'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(transcript_title)%%>', urlencode($urow['transcript_title']), $templateCode);
		$templateCode=str_replace('<%%VALUE(transcript)%%>', htmlspecialchars($row['transcript'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(transcript)%%>', urlencode($urow['transcript']), $templateCode);
		$templateCode=str_replace('<%%VALUE(credits)%%>', htmlspecialchars($row['credits'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(credits)%%>', urlencode($urow['credits']), $templateCode);
	}else{
		$templateCode=str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(author)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(author)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(bibliography_title)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(bibliography_title)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(trascriber_memberID)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(trascriber_memberID)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(transcript_title)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(transcript_title)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(transcript)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(transcript)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(credits)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(credits)%%>', urlencode(''), $templateCode);
	}

	// process translations
	foreach($Translation as $symbol=>$trans){
		$templateCode=str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}

	// clear scrap
	$templateCode=str_replace('<%%', '<!-- ', $templateCode);
	$templateCode=str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_POST['dvprint_x'] == ''){
		$templateCode .= "\n\n<script>\$j(function(){\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption){
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('[id^=\"{$name}_plink\"]').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id){
			$templateCode.="\n\tif(document.getElementById('transcriptEdit')){ document.getElementById('transcriptEdit').style.display='inline'; }";
			$templateCode.="\n\tif(document.getElementById('transcriptEditLink')){ document.getElementById('transcriptEditLink').style.display='none'; }";
			$templateCode.="\n\tif(document.getElementById('creditsEdit')){ document.getElementById('creditsEdit').style.display='inline'; }";
			$templateCode.="\n\tif(document.getElementById('creditsEditLink')){ document.getElementById('creditsEditLink').style.display='none'; }";
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';

	$templateCode.="\tauthor_update_autofills$rnd1 = function(){\n";
	$templateCode.="\t\tnew Ajax.Request(\n";
	if($dvprint){
		$templateCode.="\t\t\t'biblio_trascript_autofill.php?rnd1=$rnd1&mfk=author&id='+encodeURIComponent('".addslashes($row['author'])."'),\n";
		$templateCode.="\t\t\t{encoding: 'UTF-8', method: 'get'}\n";
	}else{
		$templateCode.="\t\t\t'biblio_trascript_autofill.php?rnd1=$rnd1&mfk=author&id=' + encodeURIComponent(current_author{$rnd1}.value),\n";
		$templateCode.="\t\t\t{encoding: 'UTF-8', method: 'get', onCreate: function(){ \$('author$rnd1').disable(); \$('authorLoading').innerHTML='<img src=loading.gif align=top>'; }, onComplete: function(){".(($arrPerm[1] || (($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3)) ? "\$('author$rnd1').enable(); " : "\$('author$rnd1').disable(); ")."\$('authorLoading').innerHTML='';}}\n";
	}
	$templateCode.="\t\t);\n";
	$templateCode.="\t};\n";
	if(!$dvprint) $templateCode.="\tif(\$('author_caption') != undefined) \$('author_caption').onchange=author_update_autofills$rnd1;\n";

	$templateCode.="\tbibliography_title_update_autofills$rnd1 = function(){\n";
	$templateCode.="\t\tnew Ajax.Request(\n";
	if($dvprint){
		$templateCode.="\t\t\t'biblio_trascript_autofill.php?rnd1=$rnd1&mfk=bibliography_title&id='+encodeURIComponent('".addslashes($row['bibliography_title'])."'),\n";
		$templateCode.="\t\t\t{encoding: 'UTF-8', method: 'get'}\n";
	}else{
		$templateCode.="\t\t\t'biblio_trascript_autofill.php?rnd1=$rnd1&mfk=bibliography_title&id=' + encodeURIComponent(current_bibliography_title{$rnd1}.value),\n";
		$templateCode.="\t\t\t{encoding: 'UTF-8', method: 'get', onCreate: function(){ \$('bibliography_title$rnd1').disable(); \$('bibliography_titleLoading').innerHTML='<img src=loading.gif align=top>'; }, onComplete: function(){".(($arrPerm[1] || (($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3)) ? "\$('bibliography_title$rnd1').enable(); " : "\$('bibliography_title$rnd1').disable(); ")."\$('bibliography_titleLoading').innerHTML='';}}\n";
	}
	$templateCode.="\t\t);\n";
	$templateCode.="\t};\n";
	if(!$dvprint) $templateCode.="\tif(\$('bibliography_title_caption') != undefined) \$('bibliography_title_caption').onchange=bibliography_title_update_autofills$rnd1;\n";


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields
	if( $_REQUEST['FilterField'][1]=='3' && $_REQUEST['FilterOperator'][1]=='<=>'){
		$templateCode.="\n<input type=hidden name=author_memberID value=\"".htmlspecialchars((get_magic_quotes_gpc() ? stripslashes($_REQUEST['FilterValue'][1]) : $_REQUEST['FilterValue'][1]))."\">\n";
	}
	if( $_REQUEST['FilterField'][1]=='4' && $_REQUEST['FilterOperator'][1]=='<=>'){
		$templateCode.="\n<input type=hidden name=bibliography_id value=\"".htmlspecialchars((get_magic_quotes_gpc() ? stripslashes($_REQUEST['FilterValue'][1]) : $_REQUEST['FilterValue'][1]))."\">\n";
	}

	// don't include blank images in lightbox gallery
	$templateCode=preg_replace('/blank.gif" rel="lightbox\[.*?\]"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	// hook: biblio_trascript_dv
	if(function_exists('biblio_trascript_dv')){
		$args=array();
		biblio_trascript_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}
?>