<?php

// Data functions for table class_dramatica_themes

// This script and data application were generated by AppGini 5.31
// Download AppGini for free from http://bigprof.com/appgini/download/

function class_dramatica_themes_insert(){
	global $Translation;

	if($_GET['insert_x']!=''){$_POST=$_GET;}

	// mm: can member insert record?
	$arrPerm=getTablePermissions('class_dramatica_themes');
	if(!$arrPerm[1]){
		return false;
	}

	$data['domain'] = makeSafe($_POST['domain']);
		if($data['domain'] == empty_lookup_value){ $data['domain'] = ''; }
	$data['concern'] = makeSafe($_POST['concern']);
		if($data['concern'] == empty_lookup_value){ $data['concern'] = ''; }
	$data['issue'] = makeSafe($_POST['issue']);
		if($data['issue'] == empty_lookup_value){ $data['issue'] = ''; }
	$data['theme'] = makeSafe($_POST['theme']);
		if($data['theme'] == empty_lookup_value){ $data['theme'] = ''; }
	$data['description'] = makeSafe($_POST['description']);
		if($data['description'] == empty_lookup_value){ $data['description'] = ''; }

	// hook: class_dramatica_themes_before_insert
	if(function_exists('class_dramatica_themes_before_insert')){
		$args=array();
		if(!class_dramatica_themes_before_insert($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('insert into `class_dramatica_themes` set       `domain`=' . (($data['domain'] !== '' && $data['domain'] !== NULL) ? "'{$data['domain']}'" : 'NULL') . ', `concern`=' . (($data['concern'] !== '' && $data['concern'] !== NULL) ? "'{$data['concern']}'" : 'NULL') . ', `issue`=' . (($data['issue'] !== '' && $data['issue'] !== NULL) ? "'{$data['issue']}'" : 'NULL') . ', `theme`=' . (($data['theme'] !== '' && $data['theme'] !== NULL) ? "'{$data['theme']}'" : 'NULL') . ', `description`=' . (($data['description'] !== '' && $data['description'] !== NULL) ? "'{$data['description']}'" : 'NULL'), $o);
	if($o['error']!=''){
		echo $o['error'];
		echo "<a href=\"class_dramatica_themes_view.php?addNew_x=1\">{$Translation['< back']}</a>";
		exit;
	}

	$recID=db_insert_id(db_link());

	// hook: class_dramatica_themes_after_insert
	if(function_exists('class_dramatica_themes_after_insert')){
		$res = sql("select * from `class_dramatica_themes` where `id`='" . makeSafe($recID) . "' limit 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID);
		$args=array();
		if(!class_dramatica_themes_after_insert($data, getMemberInfo(), $args)){ return (get_magic_quotes_gpc() ? stripslashes($recID) : $recID); }
	}

	// mm: save ownership data
	sql("insert into membership_userrecords set tableName='class_dramatica_themes', pkValue='$recID', memberID='".getLoggedMemberID()."', dateAdded='".time()."', dateUpdated='".time()."', groupID='".getLoggedGroupID()."'", $eo);

	return (get_magic_quotes_gpc() ? stripslashes($recID) : $recID);
}

function class_dramatica_themes_delete($selected_id, $AllowDeleteOfParents=false, $skipChecks=false){
	// insure referential integrity ...
	global $Translation;
	$selected_id=makeSafe($selected_id);

	// mm: can member delete record?
	$arrPerm=getTablePermissions('class_dramatica_themes');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='class_dramatica_themes' and pkValue='$selected_id'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='class_dramatica_themes' and pkValue='$selected_id'");
	if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
		// delete allowed, so continue ...
	}else{
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: class_dramatica_themes_before_delete
	if(function_exists('class_dramatica_themes_before_delete')){
		$args=array();
		if(!class_dramatica_themes_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'];
	}

	// child table: storypoints_static
	$res = sql("select `id` from `class_dramatica_themes` where `id`='$selected_id'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("select count(1) from `storypoints_static` where `problem`='".addslashes($id[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "storypoints_static", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "storypoints_static", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='class_dramatica_themes_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='class_dramatica_themes_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	// child table: storypoints_static
	$res = sql("select `id` from `class_dramatica_themes` where `id`='$selected_id'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("select count(1) from `storypoints_static` where `solution`='".addslashes($id[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "storypoints_static", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "storypoints_static", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='class_dramatica_themes_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='class_dramatica_themes_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	// child table: storypoints_static
	$res = sql("select `id` from `class_dramatica_themes` where `id`='$selected_id'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("select count(1) from `storypoints_static` where `symptom`='".addslashes($id[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "storypoints_static", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "storypoints_static", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='class_dramatica_themes_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='class_dramatica_themes_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	// child table: storypoints_static
	$res = sql("select `id` from `class_dramatica_themes` where `id`='$selected_id'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("select count(1) from `storypoints_static` where `response`='".addslashes($id[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "storypoints_static", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "storypoints_static", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='class_dramatica_themes_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='class_dramatica_themes_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	// child table: storyweaving_scenes
	$res = sql("select `id` from `class_dramatica_themes` where `id`='$selected_id'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("select count(1) from `storyweaving_scenes` where `theme`='".addslashes($id[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "storyweaving_scenes", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "storyweaving_scenes", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='class_dramatica_themes_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='class_dramatica_themes_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	sql("delete from `class_dramatica_themes` where `id`='$selected_id'", $eo);

	// hook: class_dramatica_themes_after_delete
	if(function_exists('class_dramatica_themes_after_delete')){
		$args=array();
		class_dramatica_themes_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("delete from membership_userrecords where tableName='class_dramatica_themes' and pkValue='$selected_id'", $eo);
}

function class_dramatica_themes_update($selected_id){
	global $Translation;

	if($_GET['update_x']!=''){$_POST=$_GET;}

	// mm: can member edit record?
	$arrPerm=getTablePermissions('class_dramatica_themes');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='class_dramatica_themes' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='class_dramatica_themes' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){ // allow update?
		// update allowed, so continue ...
	}else{
		return false;
	}

	$data['domain'] = makeSafe($_POST['domain']);
		if($data['domain'] == empty_lookup_value){ $data['domain'] = ''; }
	$data['concern'] = makeSafe($_POST['concern']);
		if($data['concern'] == empty_lookup_value){ $data['concern'] = ''; }
	$data['issue'] = makeSafe($_POST['issue']);
		if($data['issue'] == empty_lookup_value){ $data['issue'] = ''; }
	$data['theme'] = makeSafe($_POST['theme']);
		if($data['theme'] == empty_lookup_value){ $data['theme'] = ''; }
	$data['description'] = makeSafe($_POST['description']);
		if($data['description'] == empty_lookup_value){ $data['description'] = ''; }
	$data['selectedID']=makeSafe($selected_id);

	// hook: class_dramatica_themes_before_update
	if(function_exists('class_dramatica_themes_before_update')){
		$args=array();
		if(!class_dramatica_themes_before_update($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('update `class_dramatica_themes` set       `domain`=' . (($data['domain'] !== '' && $data['domain'] !== NULL) ? "'{$data['domain']}'" : 'NULL') . ', `concern`=' . (($data['concern'] !== '' && $data['concern'] !== NULL) ? "'{$data['concern']}'" : 'NULL') . ', `issue`=' . (($data['issue'] !== '' && $data['issue'] !== NULL) ? "'{$data['issue']}'" : 'NULL') . ', `theme`=' . (($data['theme'] !== '' && $data['theme'] !== NULL) ? "'{$data['theme']}'" : 'NULL') . ', `description`=' . (($data['description'] !== '' && $data['description'] !== NULL) ? "'{$data['description']}'" : 'NULL') . " where `id`='".makeSafe($selected_id)."'", $o);
	if($o['error']!=''){
		echo $o['error'];
		echo '<a href="class_dramatica_themes_view.php?SelectedID='.urlencode($selected_id)."\">{$Translation['< back']}</a>";
		exit;
	}


	// hook: class_dramatica_themes_after_update
	if(function_exists('class_dramatica_themes_after_update')){
		$res = sql("SELECT * FROM `class_dramatica_themes` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = $data['id'];
		$args = array();
		if(!class_dramatica_themes_after_update($data, getMemberInfo(), $args)){ return; }
	}

	// mm: update ownership data
	sql("update membership_userrecords set dateUpdated='".time()."' where tableName='class_dramatica_themes' and pkValue='".makeSafe($selected_id)."'", $eo);

}

function class_dramatica_themes_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0){
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm=getTablePermissions('class_dramatica_themes');
	if(!$arrPerm[1] && $selected_id==''){ return ''; }
	$AllowInsert = ($arrPerm[1] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != ''){
		$dvprint = true;
	}

	$filterer_domain = thisOr(undo_magic_quotes($_REQUEST['filterer_domain']), '');
	$filterer_concern = thisOr(undo_magic_quotes($_REQUEST['filterer_concern']), '');
	$filterer_issue = thisOr(undo_magic_quotes($_REQUEST['filterer_issue']), '');

	// populate filterers, starting from children to grand-parents
	if($filterer_concern && !$filterer_domain) $filterer_domain = sqlValue("select domain from class_dramatica_concern where id='" . makeSafe($filterer_concern) . "'");
	if($filterer_issue && !$filterer_domain) $filterer_domain = sqlValue("select domain from class_dramatica_issue where id='" . makeSafe($filterer_issue) . "'");
	if($filterer_issue && !$filterer_concern) $filterer_concern = sqlValue("select concern from class_dramatica_issue where id='" . makeSafe($filterer_issue) . "'");

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: domain
	$combo_domain = new DataCombo;
	// combobox: concern, filterable by: domain
	$combo_concern = new DataCombo;
	// combobox: issue, filterable by: domain,concern
	$combo_issue = new DataCombo;

	if($selected_id){
		// mm: check member permissions
		if(!$arrPerm[2]){
			return "";
		}
		// mm: who is the owner?
		$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='class_dramatica_themes' and pkValue='".makeSafe($selected_id)."'");
		$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='class_dramatica_themes' and pkValue='".makeSafe($selected_id)."'");
		if($arrPerm[2]==1 && getLoggedMemberID()!=$ownerMemberID){
			return "";
		}
		if($arrPerm[2]==2 && getLoggedGroupID()!=$ownerGroupID){
			return "";
		}

		// can edit?
		if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){
			$AllowUpdate=1;
		}else{
			$AllowUpdate=0;
		}

		$res = sql("select * from `class_dramatica_themes` where `id`='".makeSafe($selected_id)."'", $eo);
		if(!($row = db_fetch_array($res))){
			return error_message($Translation['No records found']);
		}
		$urow = $row; /* unsanitized data */
		$hc = new CI_Input();
		$row = $hc->xss_clean($row); /* sanitize data */
		$combo_domain->SelectedData = $row['domain'];
		$combo_concern->SelectedData = $row['concern'];
		$combo_issue->SelectedData = $row['issue'];
	}else{
		$combo_domain->SelectedData = $filterer_domain;
		$combo_concern->SelectedData = $filterer_concern;
		$combo_issue->SelectedData = $filterer_issue;
	}
	$combo_domain->HTML = '<span id="domain-container' . $rnd1 . '"></span><input type="hidden" name="domain" id="domain' . $rnd1 . '">';
	$combo_domain->MatchText = '<span id="domain-container-readonly' . $rnd1 . '"></span><input type="hidden" name="domain" id="domain' . $rnd1 . '">';
	$combo_concern->HTML = '<span id="concern-container' . $rnd1 . '"></span><input type="hidden" name="concern" id="concern' . $rnd1 . '">';
	$combo_concern->MatchText = '<span id="concern-container-readonly' . $rnd1 . '"></span><input type="hidden" name="concern" id="concern' . $rnd1 . '">';
	$combo_issue->HTML = '<span id="issue-container' . $rnd1 . '"></span><input type="hidden" name="issue" id="issue' . $rnd1 . '">';
	$combo_issue->MatchText = '<span id="issue-container-readonly' . $rnd1 . '"></span><input type="hidden" name="issue" id="issue' . $rnd1 . '">';

	ob_start();
	?>

	<script>
		// initial lookup values
		var current_domain__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['domain'] : $filterer_domain); ?>"};
		var current_concern__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['concern'] : $filterer_concern); ?>"};
		var current_issue__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['issue'] : $filterer_issue); ?>"};

		jQuery(function() {
			if(typeof(domain_reload__RAND__) == 'function') domain_reload__RAND__();
			<?php echo (!$AllowUpdate || $dvprint ? 'if(typeof(concern_reload__RAND__) == \'function\') concern_reload__RAND__(current_domain__RAND__.value);' : ''); ?>
			<?php echo (!$AllowUpdate || $dvprint ? 'if(typeof(issue_reload__RAND__) == \'function\') issue_reload__RAND__(current_domain__RAND__.value, current_concern__RAND__.value);' : ''); ?>
		});
		function domain_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			jQuery("#domain-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					jQuery.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: current_domain__RAND__.value, t: 'class_dramatica_themes', f: 'domain' }
					}).done(function(resp){
						c({
							id: resp.results[0].id,
							text: resp.results[0].text
						});
						jQuery('[name="domain"]').val(resp.results[0].id);
						jQuery('[id=domain-container-readonly__RAND__]').html('<span id="domain-match-text">' + resp.results[0].text + '</span>');

						if(typeof(concern_reload__RAND__) == 'function') concern_reload__RAND__(current_domain__RAND__.value);

						if(typeof(domain_update_autofills__RAND__) == 'function') domain_update_autofills__RAND__();
					});
				},
				width: '100%',
				formatNoMatches: function(term){ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 10,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ return { s: term, p: page, t: 'class_dramatica_themes', f: 'domain' }; },
					results: function(resp, page){ return resp; }
				}
			}).on('change', function(e){
				current_domain__RAND__.value = e.added.id;
				current_domain__RAND__.text = e.added.text;
				jQuery('[name="domain"]').val(e.added.id);

						if(typeof(concern_reload__RAND__) == 'function') concern_reload__RAND__(current_domain__RAND__.value);

				if(typeof(domain_update_autofills__RAND__) == 'function') domain_update_autofills__RAND__();
			});
		<?php }else{ ?>

			jQuery.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: current_domain__RAND__.value, t: 'class_dramatica_themes', f: 'domain' }
			}).done(function(resp){
				jQuery('[id=domain-container__RAND__], [id=domain-container-readonly__RAND__]').html('<span id="domain-match-text">' + resp.results[0].text + '</span>');

				if(typeof(domain_update_autofills__RAND__) == 'function') domain_update_autofills__RAND__();
			});
		<?php } ?>

		}
		function concern_reload__RAND__(filterer_domain){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			jQuery("#concern-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					jQuery.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { filterer_domain: filterer_domain, id: current_concern__RAND__.value, t: 'class_dramatica_themes', f: 'concern' }
					}).done(function(resp){
						c({
							id: resp.results[0].id,
							text: resp.results[0].text
						});
						jQuery('[name="concern"]').val(resp.results[0].id);
						jQuery('[id=concern-container-readonly__RAND__]').html('<span id="concern-match-text">' + resp.results[0].text + '</span>');

						if(typeof(issue_reload__RAND__) == 'function') issue_reload__RAND__($F('domain'), current_concern__RAND__.value);

						if(typeof(concern_update_autofills__RAND__) == 'function') concern_update_autofills__RAND__();
					});
				},
				width: '100%',
				formatNoMatches: function(term){ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 10,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ return { filterer_domain: filterer_domain, s: term, p: page, t: 'class_dramatica_themes', f: 'concern' }; },
					results: function(resp, page){ return resp; }
				}
			}).on('change', function(e){
				current_concern__RAND__.value = e.added.id;
				current_concern__RAND__.text = e.added.text;
				jQuery('[name="concern"]').val(e.added.id);

						if(typeof(issue_reload__RAND__) == 'function') issue_reload__RAND__($F('domain'), current_concern__RAND__.value);

				if(typeof(concern_update_autofills__RAND__) == 'function') concern_update_autofills__RAND__();
			});
		<?php }else{ ?>

			jQuery.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: current_concern__RAND__.value, t: 'class_dramatica_themes', f: 'concern' }
			}).done(function(resp){
				jQuery('[id=concern-container__RAND__], [id=concern-container-readonly__RAND__]').html('<span id="concern-match-text">' + resp.results[0].text + '</span>');

				if(typeof(concern_update_autofills__RAND__) == 'function') concern_update_autofills__RAND__();
			});
		<?php } ?>

		}
		function issue_reload__RAND__(filterer_domain, filterer_concern){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			jQuery("#issue-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					jQuery.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { filterer_domain: filterer_domain, filterer_concern: filterer_concern, id: current_issue__RAND__.value, t: 'class_dramatica_themes', f: 'issue' }
					}).done(function(resp){
						c({
							id: resp.results[0].id,
							text: resp.results[0].text
						});
						jQuery('[name="issue"]').val(resp.results[0].id);
						jQuery('[id=issue-container-readonly__RAND__]').html('<span id="issue-match-text">' + resp.results[0].text + '</span>');


						if(typeof(issue_update_autofills__RAND__) == 'function') issue_update_autofills__RAND__();
					});
				},
				width: '100%',
				formatNoMatches: function(term){ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 10,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ return { filterer_domain: filterer_domain, filterer_concern: filterer_concern, s: term, p: page, t: 'class_dramatica_themes', f: 'issue' }; },
					results: function(resp, page){ return resp; }
				}
			}).on('change', function(e){
				current_issue__RAND__.value = e.added.id;
				current_issue__RAND__.text = e.added.text;
				jQuery('[name="issue"]').val(e.added.id);


				if(typeof(issue_update_autofills__RAND__) == 'function') issue_update_autofills__RAND__();
			});
		<?php }else{ ?>

			jQuery.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: current_issue__RAND__.value, t: 'class_dramatica_themes', f: 'issue' }
			}).done(function(resp){
				jQuery('[id=issue-container__RAND__], [id=issue-container-readonly__RAND__]').html('<span id="issue-match-text">' + resp.results[0].text + '</span>');

				if(typeof(issue_update_autofills__RAND__) == 'function') issue_update_autofills__RAND__();
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_contents());
	ob_end_clean();


	// code for template based detail view forms

	// open the detail view template
	if($dvprint){
		$templateCode = @file_get_contents('./templates/class_dramatica_themes_templateDVP.html');
	}else{
		$templateCode = @file_get_contents('./templates/class_dramatica_themes_templateDV.html');
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Detail View', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', ($_REQUEST['Embedded'] ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert){
		if(!$selected_id) $templateCode=str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return class_dramatica_themes_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return class_dramatica_themes_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	}else{
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']){
		$backAction = 'window.parent.jQuery(\'.modal\').modal(\'hide\'); return false;';
	}else{
		$backAction = '$$(\'form\')[0].writeAttribute(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id){
		if(!$_REQUEST['Embedded']) $templateCode=str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$$(\'form\')[0].writeAttribute(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate){
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return class_dramatica_themes_validateData();"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		}else{
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		}else{
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	}else{
		$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)){
		$jsReadOnly .= "\tjQuery('#domain').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#domain_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#concern').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#concern_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#issue').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#issue_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#theme').replaceWith('<p class=\"form-control-static\" id=\"theme\">' + (jQuery('#theme').val() || '') + '</p>');\n";
		$jsReadOnly .= "\tjQuery('#description').replaceWith('<p class=\"form-control-static\" id=\"description\">' + (jQuery('#description').val() || '') + '</p>');\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	}elseif($AllowInsert){
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
			$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode=str_replace('<%%COMBO(domain)%%>', $combo_domain->HTML, $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(domain)%%>', $combo_domain->MatchText, $templateCode);
	$templateCode=str_replace('<%%URLCOMBOTEXT(domain)%%>', urlencode($combo_domain->MatchText), $templateCode);
	$templateCode=str_replace('<%%COMBO(concern)%%>', $combo_concern->HTML, $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(concern)%%>', $combo_concern->MatchText, $templateCode);
	$templateCode=str_replace('<%%URLCOMBOTEXT(concern)%%>', urlencode($combo_concern->MatchText), $templateCode);
	$templateCode=str_replace('<%%COMBO(issue)%%>', $combo_issue->HTML, $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(issue)%%>', $combo_issue->MatchText, $templateCode);
	$templateCode=str_replace('<%%URLCOMBOTEXT(issue)%%>', urlencode($combo_issue->MatchText), $templateCode);

	// process foreign key links
	if($selected_id){
		$templateCode=str_replace('<%%PLINK(domain)%%>', ($combo_domain->SelectedData ? "<span id=\"class_dramatica_domain_plink1\" class=\"hidden\"><a class=\"btn btn-default\" href=\"class_dramatica_domain_view.php?SelectedID=" . urlencode($combo_domain->SelectedData) . "\"><i class=\"glyphicon glyphicon-search\"></i></a></span>" : ''), $templateCode);
		$templateCode=str_replace('<%%PLINK(concern)%%>', ($combo_concern->SelectedData ? "<span id=\"class_dramatica_concern_plink2\" class=\"hidden\"><a class=\"btn btn-default\" href=\"class_dramatica_concern_view.php?SelectedID=" . urlencode($combo_concern->SelectedData) . "\"><i class=\"glyphicon glyphicon-search\"></i></a></span>" : ''), $templateCode);
		$templateCode=str_replace('<%%PLINK(issue)%%>', ($combo_issue->SelectedData ? "<span id=\"class_dramatica_issue_plink3\" class=\"hidden\"><a class=\"btn btn-default\" href=\"class_dramatica_issue_view.php?SelectedID=" . urlencode($combo_issue->SelectedData) . "\"><i class=\"glyphicon glyphicon-search\"></i></a></span>" : ''), $templateCode);
	}

	// process images
	$templateCode=str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(domain)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(concern)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(issue)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(theme)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(description)%%>', '', $templateCode);

	// process values
	if($selected_id){
		$templateCode=str_replace('<%%VALUE(id)%%>', htmlspecialchars($row['id'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		$templateCode=str_replace('<%%VALUE(domain)%%>', htmlspecialchars($row['domain'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(domain)%%>', urlencode($urow['domain']), $templateCode);
		$templateCode=str_replace('<%%VALUE(concern)%%>', htmlspecialchars($row['concern'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(concern)%%>', urlencode($urow['concern']), $templateCode);
		$templateCode=str_replace('<%%VALUE(issue)%%>', htmlspecialchars($row['issue'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(issue)%%>', urlencode($urow['issue']), $templateCode);
		$templateCode=str_replace('<%%VALUE(theme)%%>', htmlspecialchars($row['theme'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(theme)%%>', urlencode($urow['theme']), $templateCode);
		$templateCode=str_replace('<%%VALUE(description)%%>', htmlspecialchars($row['description'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(description)%%>', urlencode($urow['description']), $templateCode);
	}else{
		$templateCode=str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(domain)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(domain)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(concern)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(concern)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(issue)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(issue)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(theme)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(theme)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(description)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(description)%%>', urlencode(''), $templateCode);
	}

	// process translations
	foreach($Translation as $symbol=>$trans){
		$templateCode=str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}

	// clear scrap
	$templateCode=str_replace('<%%', '<!-- ', $templateCode);
	$templateCode=str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_POST['dvprint_x'] == ''){
		$templateCode .= "\n\n<script>\$j(function(){\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption){
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('[id^=\"{$name}_plink\"]').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id){
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode=preg_replace('/blank.gif" rel="lightbox\[.*?\]"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	// hook: class_dramatica_themes_dv
	if(function_exists('class_dramatica_themes_dv')){
		$args=array();
		class_dramatica_themes_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}
?>