<?php
// This script and data application were generated by AppGini 5.31
// Download AppGini for free from http://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/class_character_element.php");
	include("$currDir/class_character_element_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('class_character_element');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "class_character_element";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV=array(   
		"`class_character_element`.`id`" => "id",
		"`class_character_element`.`element`" => "element",
		"`class_character_element`.`value`" => "value"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`class_character_element`.`id`',
		2 => 2,
		3 => 3
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV=array(   
		"`class_character_element`.`id`" => "id",
		"`class_character_element`.`element`" => "element",
		"`class_character_element`.`value`" => "value"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters=array(   
		"`class_character_element`.`id`" => "ID",
		"`class_character_element`.`element`" => "Element",
		"`class_character_element`.`value`" => "Value"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS=array(   
		"`class_character_element`.`id`" => "id",
		"`class_character_element`.`element`" => "element",
		"`class_character_element`.`value`" => "value"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array();

	$x->QueryFrom="`class_character_element` ";
	$x->QueryWhere='';
	$x->QueryOrder='';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "class_character_element_view.php";
	$x->RedirectAfterInsert = "class_character_element_view.php?SelectedID=#ID#";
	$x->TableTitle = "Character elements";
	$x->TableIcon = "table.gif";
	$x->PrimaryKey = "`class_character_element`.`id`";

	$x->ColWidth   = array(  150, 150);
	$x->ColCaption = array("Element", "Value");
	$x->ColFieldName = array('element', 'value');
	$x->ColNumber  = array(2, 3);

	$x->Template = 'templates/class_character_element_templateTV.html';
	$x->SelectedTemplate = 'templates/class_character_element_templateTVS.html';
	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `class_character_element`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='class_character_element' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `class_character_element`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='class_character_element' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`class_character_element`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: class_character_element_init
	$render=TRUE;
	if(function_exists('class_character_element_init')){
		$args=array();
		$render=class_character_element_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: class_character_element_header
	$headerCode='';
	if(function_exists('class_character_element_header')){
		$args=array();
		$headerCode=class_character_element_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: class_character_element_footer
	$footerCode='';
	if(function_exists('class_character_element_footer')){
		$args=array();
		$footerCode=class_character_element_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>