<?php
// This script and data application were generated by AppGini 5.31
// Download AppGini for free from http://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/storypoints_static.php");
	include("$currDir/storypoints_static_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('storypoints_static');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "storypoints_static";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV=array(   
		"`storypoints_static`.`id`" => "id",
		"IF(    CHAR_LENGTH(`story1`.`id`) || CHAR_LENGTH(`story1`.`story`), CONCAT_WS('',   `story1`.`id`, '  ', `story1`.`story`), '') /* Story */" => "story",
		"IF(    CHAR_LENGTH(`class_dramatica_throughline1`.`throughline`), CONCAT_WS('',   `class_dramatica_throughline1`.`throughline`), '') /* Throughline */" => "throughline",
		"IF(    CHAR_LENGTH(`class_dramatica_domain1`.`domain`), CONCAT_WS('',   `class_dramatica_domain1`.`domain`), '') /* Domain */" => "throughline_domain",
		"IF(    CHAR_LENGTH(`class_dramatica_concern1`.`concern`), CONCAT_WS('',   `class_dramatica_concern1`.`concern`), '') /* Concern */" => "concern",
		"IF(    CHAR_LENGTH(`class_dramatica_issue1`.`issue`), CONCAT_WS('',   `class_dramatica_issue1`.`issue`), '') /* Issue */" => "issue",
		"IF(    CHAR_LENGTH(`class_dramatica_themes1`.`theme`), CONCAT_WS('',   `class_dramatica_themes1`.`theme`), '') /* Problem */" => "problem",
		"IF(    CHAR_LENGTH(`class_dramatica_themes2`.`theme`), CONCAT_WS('',   `class_dramatica_themes2`.`theme`), '') /* Solution */" => "solution",
		"IF(    CHAR_LENGTH(`class_dramatica_themes3`.`theme`), CONCAT_WS('',   `class_dramatica_themes3`.`theme`), '') /* Symptom */" => "symptom",
		"IF(    CHAR_LENGTH(`class_dramatica_themes4`.`theme`), CONCAT_WS('',   `class_dramatica_themes4`.`theme`), '') /* Response */" => "response",
		"IF(    CHAR_LENGTH(`class_dramatica_issue2`.`issue`), CONCAT_WS('',   `class_dramatica_issue2`.`issue`), '') /* Catalyst */" => "catalyst",
		"IF(    CHAR_LENGTH(`class_dramatica_issue3`.`issue`), CONCAT_WS('',   `class_dramatica_issue3`.`issue`), '') /* Inhibitor */" => "inhibitor",
		"IF(    CHAR_LENGTH(`class_dramatica_concern2`.`concern`), CONCAT_WS('',   `class_dramatica_concern2`.`concern`), '') /* Benchmark */" => "benchmark"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`storypoints_static`.`id`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => 6,
		7 => 7,
		8 => 8,
		9 => 9,
		10 => 10,
		11 => 11,
		12 => 12,
		13 => 13
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV=array(   
		"`storypoints_static`.`id`" => "id",
		"IF(    CHAR_LENGTH(`story1`.`id`) || CHAR_LENGTH(`story1`.`story`), CONCAT_WS('',   `story1`.`id`, '  ', `story1`.`story`), '') /* Story */" => "story",
		"IF(    CHAR_LENGTH(`class_dramatica_throughline1`.`throughline`), CONCAT_WS('',   `class_dramatica_throughline1`.`throughline`), '') /* Throughline */" => "throughline",
		"IF(    CHAR_LENGTH(`class_dramatica_domain1`.`domain`), CONCAT_WS('',   `class_dramatica_domain1`.`domain`), '') /* Domain */" => "throughline_domain",
		"IF(    CHAR_LENGTH(`class_dramatica_concern1`.`concern`), CONCAT_WS('',   `class_dramatica_concern1`.`concern`), '') /* Concern */" => "concern",
		"IF(    CHAR_LENGTH(`class_dramatica_issue1`.`issue`), CONCAT_WS('',   `class_dramatica_issue1`.`issue`), '') /* Issue */" => "issue",
		"IF(    CHAR_LENGTH(`class_dramatica_themes1`.`theme`), CONCAT_WS('',   `class_dramatica_themes1`.`theme`), '') /* Problem */" => "problem",
		"IF(    CHAR_LENGTH(`class_dramatica_themes2`.`theme`), CONCAT_WS('',   `class_dramatica_themes2`.`theme`), '') /* Solution */" => "solution",
		"IF(    CHAR_LENGTH(`class_dramatica_themes3`.`theme`), CONCAT_WS('',   `class_dramatica_themes3`.`theme`), '') /* Symptom */" => "symptom",
		"IF(    CHAR_LENGTH(`class_dramatica_themes4`.`theme`), CONCAT_WS('',   `class_dramatica_themes4`.`theme`), '') /* Response */" => "response",
		"IF(    CHAR_LENGTH(`class_dramatica_issue2`.`issue`), CONCAT_WS('',   `class_dramatica_issue2`.`issue`), '') /* Catalyst */" => "catalyst",
		"IF(    CHAR_LENGTH(`class_dramatica_issue3`.`issue`), CONCAT_WS('',   `class_dramatica_issue3`.`issue`), '') /* Inhibitor */" => "inhibitor",
		"IF(    CHAR_LENGTH(`class_dramatica_concern2`.`concern`), CONCAT_WS('',   `class_dramatica_concern2`.`concern`), '') /* Benchmark */" => "benchmark"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters=array(   
		"`storypoints_static`.`id`" => "id",
		"IF(    CHAR_LENGTH(`story1`.`id`) || CHAR_LENGTH(`story1`.`story`), CONCAT_WS('',   `story1`.`id`, '  ', `story1`.`story`), '') /* Story */" => "Story",
		"IF(    CHAR_LENGTH(`class_dramatica_throughline1`.`throughline`), CONCAT_WS('',   `class_dramatica_throughline1`.`throughline`), '') /* Throughline */" => "Throughline",
		"IF(    CHAR_LENGTH(`class_dramatica_domain1`.`domain`), CONCAT_WS('',   `class_dramatica_domain1`.`domain`), '') /* Domain */" => "Domain",
		"IF(    CHAR_LENGTH(`class_dramatica_concern1`.`concern`), CONCAT_WS('',   `class_dramatica_concern1`.`concern`), '') /* Concern */" => "Concern",
		"IF(    CHAR_LENGTH(`class_dramatica_issue1`.`issue`), CONCAT_WS('',   `class_dramatica_issue1`.`issue`), '') /* Issue */" => "Issue",
		"IF(    CHAR_LENGTH(`class_dramatica_themes1`.`theme`), CONCAT_WS('',   `class_dramatica_themes1`.`theme`), '') /* Problem */" => "Problem",
		"IF(    CHAR_LENGTH(`class_dramatica_themes2`.`theme`), CONCAT_WS('',   `class_dramatica_themes2`.`theme`), '') /* Solution */" => "Solution",
		"IF(    CHAR_LENGTH(`class_dramatica_themes3`.`theme`), CONCAT_WS('',   `class_dramatica_themes3`.`theme`), '') /* Symptom */" => "Symptom",
		"IF(    CHAR_LENGTH(`class_dramatica_themes4`.`theme`), CONCAT_WS('',   `class_dramatica_themes4`.`theme`), '') /* Response */" => "Response",
		"IF(    CHAR_LENGTH(`class_dramatica_issue2`.`issue`), CONCAT_WS('',   `class_dramatica_issue2`.`issue`), '') /* Catalyst */" => "Catalyst",
		"IF(    CHAR_LENGTH(`class_dramatica_issue3`.`issue`), CONCAT_WS('',   `class_dramatica_issue3`.`issue`), '') /* Inhibitor */" => "Inhibitor",
		"IF(    CHAR_LENGTH(`class_dramatica_concern2`.`concern`), CONCAT_WS('',   `class_dramatica_concern2`.`concern`), '') /* Benchmark */" => "Benchmark"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS=array(   
		"`storypoints_static`.`id`" => "id",
		"IF(    CHAR_LENGTH(`story1`.`id`) || CHAR_LENGTH(`story1`.`story`), CONCAT_WS('',   `story1`.`id`, '  ', `story1`.`story`), '') /* Story */" => "story",
		"IF(    CHAR_LENGTH(`class_dramatica_throughline1`.`throughline`), CONCAT_WS('',   `class_dramatica_throughline1`.`throughline`), '') /* Throughline */" => "throughline",
		"IF(    CHAR_LENGTH(`class_dramatica_domain1`.`domain`), CONCAT_WS('',   `class_dramatica_domain1`.`domain`), '') /* Domain */" => "throughline_domain",
		"IF(    CHAR_LENGTH(`class_dramatica_concern1`.`concern`), CONCAT_WS('',   `class_dramatica_concern1`.`concern`), '') /* Concern */" => "concern",
		"IF(    CHAR_LENGTH(`class_dramatica_issue1`.`issue`), CONCAT_WS('',   `class_dramatica_issue1`.`issue`), '') /* Issue */" => "issue",
		"IF(    CHAR_LENGTH(`class_dramatica_themes1`.`theme`), CONCAT_WS('',   `class_dramatica_themes1`.`theme`), '') /* Problem */" => "problem",
		"IF(    CHAR_LENGTH(`class_dramatica_themes2`.`theme`), CONCAT_WS('',   `class_dramatica_themes2`.`theme`), '') /* Solution */" => "solution",
		"IF(    CHAR_LENGTH(`class_dramatica_themes3`.`theme`), CONCAT_WS('',   `class_dramatica_themes3`.`theme`), '') /* Symptom */" => "symptom",
		"IF(    CHAR_LENGTH(`class_dramatica_themes4`.`theme`), CONCAT_WS('',   `class_dramatica_themes4`.`theme`), '') /* Response */" => "response",
		"IF(    CHAR_LENGTH(`class_dramatica_issue2`.`issue`), CONCAT_WS('',   `class_dramatica_issue2`.`issue`), '') /* Catalyst */" => "catalyst",
		"IF(    CHAR_LENGTH(`class_dramatica_issue3`.`issue`), CONCAT_WS('',   `class_dramatica_issue3`.`issue`), '') /* Inhibitor */" => "inhibitor",
		"IF(    CHAR_LENGTH(`class_dramatica_concern2`.`concern`), CONCAT_WS('',   `class_dramatica_concern2`.`concern`), '') /* Benchmark */" => "benchmark"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array(  'story' => 'Story', 'throughline' => 'Throughline', 'throughline_domain' => 'Domain', 'concern' => 'Concern', 'issue' => 'Issue', 'problem' => 'Problem', 'solution' => 'Solution', 'symptom' => 'Symptom', 'response' => 'Response', 'catalyst' => 'Catalyst', 'inhibitor' => 'Inhibitor', 'benchmark' => 'Benchmark');

	$x->QueryFrom="`storypoints_static` LEFT JOIN `story` as story1 ON `story1`.`id`=`storypoints_static`.`story` LEFT JOIN `class_dramatica_throughline` as class_dramatica_throughline1 ON `class_dramatica_throughline1`.`id`=`storypoints_static`.`throughline` LEFT JOIN `class_dramatica_domain` as class_dramatica_domain1 ON `class_dramatica_domain1`.`id`=`storypoints_static`.`throughline_domain` LEFT JOIN `class_dramatica_concern` as class_dramatica_concern1 ON `class_dramatica_concern1`.`id`=`storypoints_static`.`concern` LEFT JOIN `class_dramatica_issue` as class_dramatica_issue1 ON `class_dramatica_issue1`.`id`=`storypoints_static`.`issue` LEFT JOIN `class_dramatica_themes` as class_dramatica_themes1 ON `class_dramatica_themes1`.`id`=`storypoints_static`.`problem` LEFT JOIN `class_dramatica_themes` as class_dramatica_themes2 ON `class_dramatica_themes2`.`id`=`storypoints_static`.`solution` LEFT JOIN `class_dramatica_themes` as class_dramatica_themes3 ON `class_dramatica_themes3`.`id`=`storypoints_static`.`symptom` LEFT JOIN `class_dramatica_themes` as class_dramatica_themes4 ON `class_dramatica_themes4`.`id`=`storypoints_static`.`response` LEFT JOIN `class_dramatica_issue` as class_dramatica_issue2 ON `class_dramatica_issue2`.`id`=`storypoints_static`.`catalyst` LEFT JOIN `class_dramatica_issue` as class_dramatica_issue3 ON `class_dramatica_issue3`.`id`=`storypoints_static`.`inhibitor` LEFT JOIN `class_dramatica_concern` as class_dramatica_concern2 ON `class_dramatica_concern2`.`id`=`storypoints_static`.`benchmark` ";
	$x->QueryWhere='';
	$x->QueryOrder='';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "storypoints_static_view.php";
	$x->RedirectAfterInsert = "storypoints_static_view.php";
	$x->TableTitle = "Storypoints";
	$x->TableIcon = "table.gif";
	$x->PrimaryKey = "`storypoints_static`.`id`";

	$x->ColWidth   = array(  150, 150, 150, 150, 150, 150, 150);
	$x->ColCaption = array("id", "Story", "Throughline", "Domain", "Concern", "Issue", "Problem");
	$x->ColFieldName = array('id', 'story', 'throughline', 'throughline_domain', 'concern', 'issue', 'problem');
	$x->ColNumber  = array(1, 2, 3, 4, 5, 6, 7);

	$x->Template = 'templates/storypoints_static_templateTV.html';
	$x->SelectedTemplate = 'templates/storypoints_static_templateTVS.html';
	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `storypoints_static`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='storypoints_static' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `storypoints_static`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='storypoints_static' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`storypoints_static`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: storypoints_static_init
	$render=TRUE;
	if(function_exists('storypoints_static_init')){
		$args=array();
		$render=storypoints_static_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: storypoints_static_header
	$headerCode='';
	if(function_exists('storypoints_static_header')){
		$args=array();
		$headerCode=storypoints_static_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: storypoints_static_footer
	$footerCode='';
	if(function_exists('storypoints_static_footer')){
		$args=array();
		$footerCode=storypoints_static_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>